### ISSUE TITLE
Some strange mm results

### ISSUE THREAD

**Issue by windingwind** [cyang-kth/fmm#100]
Here are some strange mm results I found on the Porto taxi trajectory dataset:
In images below, blue markers are the origin input points, polylines are mm result. All results use default configurations.

### points are close and have small turn-back
![image](https://user-images.githubusercontent.com/33902321/89747724-9a117e80-daf2-11ea-9318-41fc30d421bd.png)
![image](https://user-images.githubusercontent.com/33902321/89747726-9c73d880-daf2-11ea-8cd1-0c48ac258045.png)
As shown in img2, points to the left side of img1 are marked in the timestamp sequence. The result seems incorrect, for the time interval between each point is 15s, so it is impossible for the taxi to drive that route.

### outlier points
![image](https://user-images.githubusercontent.com/33902321/89748295-160cc600-daf5-11ea-83f0-44f7ea56fed2.png)
Outlier points to the right side of the image above cause a strange mm result. 

Maybe I should use the 'vamx' configuration? And how to get the length of map unit?

**Comment by cyang-kth** [comment]
@windingwind 

Thank you for highlighting those cases. The reverse movement is discussed at this issue #98. 
As for the outlier points, it is hard for the program to detect some errors in the matching, so maybe some kinds of preprocessing should be applied to filter out those outliers.

**Comment by windingwind** [comment]
Thanks for replying!
