### ISSUE TITLE
Support multithread and distributed

### ISSUE THREAD

**Issue by windingwind** [cyang-kth/fmm#101]
It is time-costing to do mm in a big dataset. Doing mm using FMM's stmatch in a dataset with over 1 million trajectories will cost about 3,000 hours. However, the CPU usage is only 10%. Will it be possible to support multithread or distributed in the future?

**Comment by cyang-kth** [comment]
You can add the option `--use_omp` to turn on the multithreaded matching. 

https://github.com/cyang-kth/fmm/tree/master/example/command_line_example
```bash
# XML configuration
fmm fmm_config_omp.xml
# Command line arguments
fmm --ubodt ../data/ubodt.txt --network ../data/edges.shp --gps ../data/gps.csv --gps_point -k 4 -r 0.4 -e 0.5 --output mr.txt --use_omp
```

The same option applies to stmatch program. 

If your network is not that big, you can use ubodt_gen to precompute a table `ubodt.txt` and then use fmm to perform the matching, which is much faster than stmatch.

**Comment by windingwind** [comment]
Thanks a lot! I'll try this.
