### ISSUE TITLE
Match not made when input contains a small spur

### ISSUE THREAD

**Issue by jczaplew** [cyang-kth/fmm#106]
**Describe the bug**
I have the given [network](https://www.dropbox.com/s/piuubq95n2b43sc/network.zip?dl=0
):

<img width="914" alt="image" src="https://user-images.githubusercontent.com/1739551/91107005-cfad8000-e639-11ea-8fe8-bb474cc8dac6.png">

And two almost identical GPS tracks. The first looks like this:

````json
{ "type": "Feature", "properties": { "id": 1 }, "geometry": { "type": "LineString", "coordinates": [ [ -91.71373, 43.665048 ], [ -91.71039, 43.66543 ], [ -91.707559, 43.668197 ], [ -91.704283, 43.668197 ], [ -91.703361, 43.66718 ], [ -91.700498, 43.667339 ], [ -91.69913, 43.668166 ], [ -91.697412, 43.668038 ] ]  } }
````

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/1739551/91107064-f66bb680-e639-11ea-8820-1472d32e235f.png">

The second is identical to the first, but it contains a very small spur at one end:

````json
{ "type": "Feature", "properties": { "id": 1 }, "geometry": { "type": "LineString", "coordinates":  [ [ -91.71373, 43.665048 ], [ -91.71039, 43.66543 ], [ -91.707559, 43.668197 ], [ -91.704283, 43.668197 ], [ -91.703361, 43.66718 ], [ -91.700498, 43.667339 ], [ -91.69913, 43.668166 ], [ -91.697412, 43.668038 ], [ -91.697412, 43.668049 ], [ -91.697412, 43.668049 ] ]  } }
````

<img width="742" alt="image" src="https://user-images.githubusercontent.com/1739551/91107126-17cca280-e63a-11ea-9dd6-d8ccb9edbf9f.png">

Using the following code adapted from your excellent [OSM map matching tutorial](https://github.com/cyang-kth/osm_mapmatching#2-run-map-matching-with-fmm), the first GPS track successfully matches the network, but the second does not:

````python

from fmm import FastMapMatch
from fmm import Network
from fmm import NetworkGraph
from fmm import UBODTGenAlgorithm
from fmm import UBODT
from fmm import FastMapMatchConfig
import json
from shapely.geometry import shape
from shapely import wkt

### Read network data
network = Network("network/edges.shp", "fid", "u", "v")
graph = NetworkGraph(network)

### Precompute an UBODT table

# Can be skipped if you already generated an ubodt file
ubodt_gen = UBODTGenAlgorithm(network, graph)
status = ubodt_gen.generate_ubodt("network/ubodt.txt", 0.003, binary=False, use_omp=True)

### Read UBODT

ubodt = UBODT.read_ubodt_csv("network/ubodt.txt")

### Create FMM model
model = FastMapMatch(network, graph, ubodt)

### Define map matching configurations

k = 8
radius = 0.003
gps_error = 0.005
fmm_config = FastMapMatchConfig(k, radius, gps_error)

def process_line(json_string):
    feature = json.loads(json_string)
    feature_wkt = shape(feature['geometry']).wkt

    matched_wkt = model.match_wkt(feature_wkt, fmm_config).mgeom.export_wkt()
    if matched_wkt == 'LINESTRING()':
        print('No match')
    else:
        print('Made a match')

with open('./gps.geojson', 'r') as input:
    process_line(input.readline())

with open('./gps_bad.geojson', 'r') as input:
    process_line(input.readline())
````

**Expected behavior**
I would expect both GPS tracks to match the network and have an identical, or almost identical, output

**Screenshots**
Inlined above

The network was generated by following the OSM Map Matching tutorial with `osmnx==0.15.1` and can be downloaded here - https://www.dropbox.com/s/piuubq95n2b43sc/network.zip?dl=0

**Comment by cyang-kth** [comment]
Thanks for pointing out this issue. I have reproduced the same error. I will figure out the issue soon.

**Comment by cyang-kth** [comment]
@jczaplew 

I actually found two issues here. The bad geojson cannot be matched because the spur as a **reverse movement** violates the requirement that **a vehicle should always move along an edge** (it should never turn back.)  It is also related with this issue https://github.com/cyang-kth/fmm/issues/98. 

In your example, the edge is single directed and the vehicle cannot move back on another edge. 

The reverse-movement branch (has been merged into master branch) updates the optimization function to make it more robust and also add a configuration called `--reverse_tolerance` to allow move back to some proportion.

This is the result of the good gps 

![image](https://user-images.githubusercontent.com/6810084/91163267-99214500-e6cd-11ea-962a-4ae95cccc322.png)

For the bad gps, the default result can still match it, but it will generate a turn back movement 

![image](https://user-images.githubusercontent.com/6810084/91163335-b6eeaa00-e6cd-11ea-833a-71b72b04e610.png)

After adding the `reverse_tolerance` of 0.5, the problem is corrected 

![image](https://user-images.githubusercontent.com/6810084/91163403-cec62e00-e6cd-11ea-999b-5abc950340b9.png)

**Comment by cyang-kth** [comment]
The way of adding the configuration is listed below

```python
k = 8
radius = 0.003
gps_error = 0.005
reverse_tolerance = 0.5
fmm_config2 = FastMapMatchConfig(k, radius, gps_error, reverse_tolerance)

def process_line_reverse(json_string):
    feature = json.loads(json_string)
    feature_wkt = shape(feature['geometry']).wkt

    result = model.match_wkt(feature_wkt, fmm_config2)
    matched_wkt = result.mgeom.export_wkt()
    if matched_wkt == 'LINESTRING()':
        print('No match')
    else:
        print('Made a match')
        print matched_wkt    
    return matched_wkt
```

**Comment by cyang-kth** [comment]
Another issue I found with your code is that the 

```python
matched_wkt  = model.match_wkt(feature_wkt, fmm_config).mgeom.export_wkt()
```

It will generate some weird wkt result e.g., 
```
LINESTRING(4.6867201e-310 4.6867202e-310,0 0,-91.71342 43.665155,-91.713173 43.66517,-91.713041 43.665191,-91.712991 43.665199,-91.7126 43.665166,-91.712137 43.665181,-91.711705 43.66521,-91.711327 43.665265,-91.710966 43.665359,-91.710808 43.665413,-91.710612 43.665492,-91.710322 43.665627,-91.710241 43.665669,-91.710072 43.665768,-91.709986 43.665819,-91.709614 43.666128,-91.709383 43.666375,-91.70902 43.666652,-91.708922 43.666747,-91.708676 43.667005,-91.708599 43.667095,-91.70846 43.667278,-91.708221 43.667578,1.2900897e-57 7.8678808e-67,4.7653214e-38 1.0331844e-47,2.8092305e-33 1.5882155e-47,2.0046071e-76 6.769343e-43,4.8923288e-62 9.9361052e-96,3.8534252e-57 9.9600449e-43,3.4632095e-86 1.2897809e-57,6.8201811e-38 4.7573352e-38,3.6356756e-43 4.7665143e-38,6.7719261e-43 5.2045904e-90,4.6643942e-62 9.0478257e-43,4.4298612e-62 4.5844374e-72,2.2125661e-52 1.3038882e-76,5.2017364e-90 4.2785591e-33,8.9906059e-96 5.3484949e-38,5.0522003e-86 2.9513051e+179,2.5245587e-52 1.5345061e-52,1.4000792e-76 8.9906059e-96,3.1192542e-33 3.4436009e-86,4.0827923e+179 8.9690512e-67,3.5727986e-62 5.6415215e-62,1.1329615e-95 2.4234197e-52,4.046821e-86 3.1127649e+179,1.0394502e-42 2.3414693e-57,2.1077533e-52 7.5952469e-96,4.0145941e-57 5.0522003e-86,3.7617624e+179 7.4853574e-67,1.0056539e-47 3.221162e-57,8.5279246e-96 1.5195191e-47,3.4435886e-86 2.9532245e+179,1.5700985e-76 2.8306671e-33,2.5282276e-52 8.9887771e-96,1.6925777e-52 4.2479068e-86,4.0853274e+179 1.6893229e-52,4.3192529e-38 4.1830097e-62,4.4666299e-33 2.2137895e-52,4.5833406e-72 1.2558139e-71,2.404938e-57 5.2027028e-90,2.178332e-76 1.7227025e-47,5.1382827e-321 1.0197515e-320,1.6350367e+45 1.6566278e-47,1.0853981e-71 9.9636028e-43,1.4854133e-76 1.4249369e-71,1.2900945e-57 2.2125708e-52,4.184868e-62 1.0331844e-47,1.4249369e-71 1.2831225e-153,3.314113e-33 1.3119663e-71,3.8613953e-86 4.3297482e-91)
```

Which I replace to 
```python
result = model.match_wkt(feature_wkt, fmm_config2)
matched_wkt = result.mgeom.export_wkt()
```

The reason is that the output of `match_wkt` is not a plain Python object but a wrapper of swig C++ object. In your case, it seems that the object `model.match_wkt(feature_wkt, fmm_config)` is created temporally and destroyed when you call `.mgeom` and causes weird result. Keep the `result` as a separate object seems to solve this issue.

**Comment by jczaplew** [comment]
@cyang-kth Thank you so much for the assistance! The addition of the reverse tolerance parameter is fantastic and really cleans up the results. Also thank you for pointing out the issue with the conversion to wkt - I had also noticed the very small values and figured it was related to the spur issue.
