### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by chb666** [cyang-kth/fmm#107]
**ImportError: No module named _fmm **
This probelm happens in the window 10, the example of python can be run. when I  run in the jupyter notebook(py 2.7), This probelm happens.

 
![image](https://user-images.githubusercontent.com/58622666/91865669-3408b900-eca4-11ea-9479-bef2f4728cb1.png)

**Comment by cyang-kth** [comment]
The reason can be that you have multiple version of Python installed. You need to ensure that the python used in jupyter-notebook (when you start jupter-notebook) is the same as the one used in plain python command when you type `python` in terminal.

When you install the package using `cmake ..` you should be able to see which python you are using. 
https://ci.appveyor.com/project/cyang-kth/fmm#L3348

```
-- Found PythonLibs: /usr/lib/libpython2.7.dll.a (found suitable version "2.7.18", minimum required is "2.7") 
-- Python header found at /usr/include/python2.7
-- Python library found at /usr/lib/libpython2.7.dll.a
-- Using swig add library
-- Configuring done
-- Generating done
```

You can change the python library path to anaconda if you have multiple versions through setting the two paths 
- `PYTHON_LIBRARY`: path to dll or dylib file
- `PYTHON_INCLUDE_DIR`: path to python header

Like this one and reinstall the program
```bash
cmake .. -DPYTHON_LIBRARY=/anaconda2/lib/libpython2.7.dylib -DPYTHON_INCLUDE_DIR=/anaconda2/include/python2.7
```

**Comment by chb666** [comment]
Sorry to trouble you again, I have a new problem when changing the environment
![image](https://user-images.githubusercontent.com/58622666/91934331-b2ee0800-ed1d-11ea-9a22-d8b8393a0b30.png)
Can you teach me how to solve it
thank you very much

**Comment by chb666** [comment]
Sorry to interrupt you, I ran into a new problem when changing the environment, I hope you can teach me how to solve it
![image](https://user-images.githubusercontent.com/58622666/91934709-94d4d780-ed1e-11ea-8a1d-e293064e9ec9.png)
thank you very much

**Comment by cyang-kth** [comment]
@chb666 
I think your problem is that the anaconda is in windows platform so that its python is not compatible with the cygwin system. 
I think that you can install jupyter-notebook in cygwin using 

```bash
pip install jupyter
```
Then you always need to start the jupyter from cygwin if you want to use fmm python extension.

**Comment by chb666** [comment]
I'm sorry to disturb you again. In the case of system incompatibility, I used the Ubuntu 18.04 system and there was a problem in the cmake stage.
![image](https://user-images.githubusercontent.com/58622666/92100605-967dc880-ee0e-11ea-98e9-9283f33f9bb3.png)

**Comment by cyang-kth** [comment]
From that log it is hard to find the error, you can compare your log with this one, which builds successfully on Ubuntu system

https://travis-ci.org/github/cyang-kth/fmm/jobs/720923947#L818

**Comment by cyang-kth** [comment]
@chb666 
The travis-ci deployment is tested on Ubuntu 16.04. From your log error, it seems that you are using a virtual machine of Ubuntu. Perhaps you need to increase the memory of your VM from this suggestion below. 

https://blog.csdn.net/fenquegong2126/article/details/80988452

**Comment by chb666** [comment]
> @chb666
> The travis-ci deployment is tested on Ubuntu 16.04. From your log error, it seems that you are using a virtual machine of Ubuntu. Perhaps you need to increase the memory of your VM from this suggestion below.
> 
> https://blog.csdn.net/fenquegong2126/article/details/80988452

thank you very much
