### ISSUE TITLE
cmake troubles

### ISSUE THREAD

**Issue by TMLOG** [cyang-kth/fmm#110]
I'm having trouble using the FMM installation of windows.When follow the tips of building and installing fmm on the cygwin-terminal, I'm getting the error of cmake:
![image](https://user-images.githubusercontent.com/70834990/93173849-ae830f80-f75f-11ea-85b3-23e8bdddc766.png)

**Comment by cyang-kth** [comment]
@TMLOG 

You need to follow these instructions https://fmm-wiki.github.io/docs/installation/windows.html.

Especially the following commands:

```
# Under the `fmm` folder
mkdir build
cd build
cmake ..
make -j8
make install
```

From your log it seems that you are running the command in the `fmm/python/build` folder, which is a problem. It should be `fmm/build`.

**Comment by TMLOG** [comment]
@cyang-kth 
I follow the tips above,but there is something wrong:
![image](https://user-images.githubusercontent.com/70834990/93184114-746d3a00-f76e-11ea-8846-f13a663e43f5.png)

**Comment by cyang-kth** [comment]
Have you installed all the system requirements?

```
apt-cyg install make gcc-g++ cmake gdal libboost-devel zlib-devel libgdal-devel libexpat1-devel libbz2-devel
```

You can compare your log with this one below:
https://ci.appveyor.com/project/cyang-kth/fmm?fullLog=true#L3302

**Comment by cyang-kth** [comment]
This issue is not active so I close it.
