### ISSUE TITLE
Full list of output from Python API

### ISSUE THREAD

**Issue by Jamesyang2333** [cyang-kth/fmm#111]
Is there a way to access the full list of outputs (e.g. speed, offset, length...) through the python extension? From the example in the Jupyter notebook I'm only able to get indices, pgeom, mgeom, cpath and opath. Thank you!

**Comment by Raycn0514** [comment]
To find output_config from  fmm/src/config/result_config.hpp 
:)

**Comment by Raycn0514** [comment]
> Is there a way to access the full list of outputs (e.g. speed, offset, length...) through the python extension? From the example in the Jupyter notebook I'm only able to get indices, pgeom, mgeom, cpath and opath. Thank you!

fmm/src/config/result_config.hpp

**Comment by cyang-kth** [comment]
@Jamesyang2333 

@Raycn0514 Thanks for your help. Raycn0514 mentions one way to define result config fields and then the information will be written to a file. 

You can directly access that information in Python by looking at the candidates fields of the match result defined in this file

https://github.com/cyang-kth/fmm/blob/master/src/python/pyfmm.hpp

Please have a look at this notebook, which is updated in the latest version
https://github.com/cyang-kth/fmm/blob/master/example/notebook/fmm_example.ipynb

```python

result = model.match_wkt(wkt,fmm_config)
candidates = []
for c in result.candidates:
    candidates.append((c.edge_id,c.source,c.target,c.error,c.length,c.offset,c.spdist,c.ep,c.tp))

import pandas as pd
df = pd.DataFrame(candidates,
                  columns=["eid","source","target","error","length","offset","spdist","ep","tp"])
```

You can print the dataframe information like

![image](https://user-images.githubusercontent.com/6810084/93455932-4a865580-f8dd-11ea-9873-92ff05016b03.png)

**Comment by Jamesyang2333** [comment]
That's really helpful, thank you so much!
