### ISSUE TITLE
Incompatible with boost library 1.73

### ISSUE THREAD

**Issue by cyang-kth** [cyang-kth/fmm#112]
Some library paths are removed such as `boost/detail/endian.hpp`, which cause problems on Mac installation.

**Comment by HuiLuoHuiLuo** [comment]
Can you please clarify which library paths have been removed? Because when I was trying to install it in the mac, I still meet with the errors like: 

cannot find the file "boost/detail/endian.hp"

/usr/local/include/boost/geometry/index/detail/rtree/node/variant_visitor.hpp:51:5: error: no matching function for call to 'apply_visitor'

**Comment by cyang-kth** [comment]
The first one is relatively easy to solve but the second one is problematic as it seems to be related with a bug with boost geometry. 

https://github.com/boostorg/geometry/issues/721

I think one way to solve the problem is to install/build an older version of Boost.

**Comment by cyang-kth** [comment]
@HuiLuoHuiLuo 

The official tool brew does not seem to support installing an older version of boost, you can try to build an older version manually following the steps:
1. Remove the current boost 1.73 installed by brew
```bash
brew uninstall --ignore-dependencies boost
```
2. Build the boost 1.72 following this tutorial https://www.boost.org/doc/libs/1_72_0/more/getting_started/unix-variants.html
Download the source code boost_1_72_0.tar.gz from https://www.boost.org/users/history/version_1_72_0.html
```bash
tar --bzip2 -xf boost_1_72_0.tar.gz
cd boost_1_72_0
sudo ./bootstrap.sh --prefix=/usr/local
sudo ./b2 install 
```
It may take several minutes to build the whole library. Finally I can build fmm successfully on my Mac. 

Make sure that you have the correct boost version found by `cmake ..` as
```
-- Boost headers found at /usr/local/include
-- Boost library found at Boost::serialization
-- Boost library version 1_72
```

Some other references
- Build boost from source https://stackoverflow.com/questions/22470265/how-to-install-boost-on-gnu-linux

**Comment by cyang-kth** [comment]
The dependency of wkb IO in third party is removed in this PR
https://github.com/cyang-kth/fmm/pull/148
