### ISSUE TITLE
Load network fail may cause python kernel killed

### ISSUE THREAD

**Issue by zhangpj15** [cyang-kth/fmm#117]
When I load networksusing "Network" method, the wrong file name will just kill the kernel, which is really inconvenient because I have to prepare all the stuff in the environment.
![image](https://user-images.githubusercontent.com/32196265/95337352-5665a600-08e4-11eb-80d8-04c8d4f239e4.png)

I think a better way to solve this question is to raise an error in python. In this way, I can make my correction without losing all the stuff in the environment(variables and functions).

**Comment by visile** [comment]
You can tell me how to solve the problem of "the kernel appears to have died. It will restart automatically." when processing multiple GPS data

**Comment by zhangpj15** [comment]
@visile The problem I met is that my network path is wrong. This is because my interpreter seems to only recognize absolute path rather than local path. After correcting the path, my problem is solved. I think you can recheck your path with both absolute path and local path, there should be at least one of those can help you load the network successfully.

**Comment by visile** [comment]
Thank you very much. I thought the data was too big. It seems that the data is wrong.

**Comment by cyang-kth** [comment]
This issue is solved in the above merge.
