### ISSUE TITLE
I do not have the python folder in the build path

### ISSUE THREAD

**Issue by snowman109** [cyang-kth/fmm#119]
![image](https://user-images.githubusercontent.com/26241639/95595301-982a5400-0a7e-11eb-8d8b-6602b0088e3a.png)
my python folder is in the fmm path and the build path do not have the python folder
![image](https://user-images.githubusercontent.com/26241639/95595198-7b8e1c00-0a7e-11eb-85d5-25c6ff0ce30d.png)
this is my python folder
![image](https://user-images.githubusercontent.com/26241639/95595262-8d6fbf00-0a7e-11eb-9aad-c262da20dcbc.png)
so i change the PYTHONPATH to the python folder which in the fmm path and execute the source command. That's the result:
![image](https://user-images.githubusercontent.com/26241639/95595783-256da880-0a7f-11eb-887e-04018bd11b29.png)
But i can import this package into my code.

**Comment by cyang-kth** [comment]
It seems that you are using some old version of the library. 
Did you download the latest master version? The python folder under build is generated automatically.

**Comment by snowman109** [comment]
ok，I have finished it. Thank you
