### ISSUE TITLE
Sometimes the first or last point in WKB is 0 0

### ISSUE THREAD

**Issue by skinkie** [cyang-kth/fmm#12]
For some reason the last point in the WKB is 0, 0. I would also be interested where this error comes from.

LINESTRING(15453.4104747247 378339.923357993,15453.4919999987 378340.359999999,15454.7820000015 378347.800000001,15457.2190000005 378361.861000001,15458.5720000006 378367.188999999,15460.8330000006 378371.25,15463.1059999987 378374.
807999998,15465.938000001 378377.506999999,15473.3680000007 378383.057,15479.2659999989 378386.600000002,15481.3099999987 378387.802999999,15483.8409999982 378388.245000001,15486.3850000016 378389.16,15488.3220000006 378389.548,15535
.7569999993 378399.070999999,15539.675999999 378399.857999999,0 0)

LINESTRING(0 0,22601.778 397575.571,22595.76 397568.293,22564.676 397534.956,22555.374 397526.605,22536.228 397513.27,22388.963 397445.265,22387.456 397444.569,22381.37 397437.341,22379.646 397435.294,22373.333 397423.983,22366.321 
397411.422,22366.2753544712 397410.972065502)

**Comment by cyang-kth** [comment]
Which trajectory generates this result? Can you give me an example to reproduce it?

**Comment by skinkie** [comment]
```
2256;114547798,114547901,114548289;114547798,114547901,114548289;01020000000D000000000000000000000000000000000000001283C0CA7112D6405839B4481E4418413D0AD7A3F010D6402731082C01441841068195432B09D640FCA9F1D27B4318412DB29DEFD706D640B81E856B5A431841DF4F8D970E02D64048E17A142543184183C0CAA13DDDD540F6285C0F15421841BE9F1A2FDDDCD5409EEFA74612421841E17A14AE57DBD540A01A2F5DF54118414E621058E9DAD54004560E2DED411841643BDF4F55D9D540508D97EEBF4118418195438B94D7D5409CC420B08D411841285C689F91D7D540902365E38B411841
```

**Comment by cyang-kth** [comment]
The problem occurs in some cases the offset becomes slightly bigger than the length of an edge thus the default value of 0,0 is appended to the matched geometry. The bug has been fixed now.
