### ISSUE TITLE
what are the meaning of parameters in  FMM configuration or STMATCH configuration?

### ISSUE THREAD

**Issue by visile** [cyang-kth/fmm#122]
what is the meanings of k, gps_error, radius,vmax,factor?And what are the units of them?

**Comment by cyang-kth** [comment]
You can check the link here
https://fmm-wiki.github.io/docs/documentation/configuration/

From the page: 

About map unit. The unit of search radius and gps error, vmax are assumed to be **the same as the road network shapefile**.
Both the network and gps data should be in the same reference system.
- If both the network and gps data are unprojected (in geodetic degree such as OSM and latitude, longitude), then 1 degree of latitude or longitude equals to about 111km. Search radius of 0.003 should be defined here to represent to 300 meters in reality.
- If both the network and gps data are projected in meters, Search radius of 300 corresponds to 300 meters in reality.

**Comment by visile** [comment]
thank you for you help!
