### ISSUE TITLE
Cygwin apt-cyg mirror issue

### ISSUE THREAD

**Issue by gottfriedmrs** [cyang-kth/fmm#133]
Dear Can,

I have some troubles to install packages make gcc-g++, ...

```
$ apt-cyg install make
mkdir: impossible de créer le répertoire « C:\\Program Files/Cygwin/install »: Permission denied
/usr/local/bin/apt-cyg: ligne 158 : cd: C:\Program Files\Cygwin/install/x86_64: No such file or directory
Installing make
Unable to locate package make
```

I have set the mirror as:

```
$ apt-cyg mirror "mirrors.163.com"
Mirror set to mirrors.163.com.
```

from: https://cygwin.com/mirrors.html

Thanks in advance !

**Comment by cyang-kth** [comment]
I think it is related with a permission issue. 

https://stackoverflow.com/questions/4479615/permission-denied-using-cygwin-in-windows
