### ISSUE TITLE
Installation with Conda

### ISSUE THREAD

**Issue by meshalawy** [cyang-kth/fmm#137]
Hi, 
Is there a way the library be managed and installed via Conda or pip?

**Comment by cyang-kth** [comment]
I have not figured out a way to install through pip or conda as the library use a lot of third party libraries.

However, if you have conda installed, you can install the fmm binding for the conda's Python environment by setting python header and python library to the one in conda.

**Comment by changfyg** [comment]
Hi.
Can provide the steps on how to set the python header and library to the conda's?
