### ISSUE TITLE
The returned matching result is null

### ISSUE THREAD

**Issue by visile** [cyang-kth/fmm#139]
Hello, I'm sorry to disturb you again.Because my own road network is more detailed than that downloaded by OSM, I want to use my own road network for matching. I've followed what you said, and the points is clearly on the road but the result of map matching with my own road network is null or strange.
1. ID field should be different for two reverse edge **in the road attribute table**.
2.Source target fields should be replaced for the reversed one. If one is source 1 target 2, the other one should be source 2, target 1 **in the road attribute table**.
3.The geometry of the feature should be reversed for the feature. One is LineString(1 1, 0 0, 1 2) the other one should be LineString(1 2, 0 0, 1 1)
Can I send you the data and have a look at it for me? Thank you very much.

**Comment by cyang-kth** [comment]
You can send me a link with the road network and a single trajectory that cannot be matched.

**Comment by visile** [comment]
I have sent the road network data and track data to your mailbox(cyang@kth.se). I wonder if you can receive them.

**Comment by cyang-kth** [comment]
I did not receive it. Maybe you can share it with a link of Google drive or Onedrive.

**Comment by visile** [comment]
[mapmatching_test.zip](https://github.com/cyang-kth/fmm/files/5523474/mapmatching_test.zip)
 You can download it here.Thank a lot.

**Comment by cyang-kth** [comment]
@visile 

The topology of your network seems to be wrong. 

![image](https://user-images.githubusercontent.com/6810084/98806594-b4246b00-2419-11eb-87b0-989a986a961a.png)

The trajectory moves upward but the edges are downward directed. You need to prepare a network with correct topology. 

![image](https://user-images.githubusercontent.com/6810084/98806888-26954b00-241a-11eb-8f22-c3e7b9a188b8.png)

**Comment by visile** [comment]
oh！I think it's OK to have the edge of repetition and the starting and ending points. Is the establishment and visualization of the network topology in QGIS?

**Comment by cyang-kth** [comment]
The visualization is in QGIS but the creation of topology you need to refer to PostGIS or libraries in Python.
