### ISSUE TITLE
Question about "spdist" field in output

### ISSUE THREAD

**Issue by Jamesyang2333** [cyang-kth/fmm#141]
Hi, may I know what's the unit of the shortest path distance (spdist) field in the fmm output, and how is it calculated? Is it the euclidean distance between raw GPS points, or the shortest path distance on road network?

**Comment by cyang-kth** [comment]
It is the shortest path distance  on the road network between candidates (point on the matched edge) matched to each GPS point that is displayed as violet line below. The unit is the same as the unit of network shapefile. 

<img src="https://user-images.githubusercontent.com/6810084/99245446-dfd19780-2803-11eb-86a5-b3d302a4c556.png" width="600px">

**Comment by Jamesyang2333** [comment]
I see, thank you!
