### ISSUE TITLE
the output issue

### ISSUE THREAD

**Issue by M-Efforts** [cyang-kth/fmm#144]
Hello, I would like to ask why the SPdist of the two GPS points I output is very small, with an order of 10-4? How can I turn it into a meter scale? For example, if I put in two coordinates (34.231594, 108.927851) and (34.231584, 108.92837), I get the “spdist ” is 0.000519009, is this result right?

**Comment by cyang-kth** [comment]
The unit is in degree and you need to convert to meter by multiplied with 1.1x10^5 for approximation. 
https://github.com/cyang-kth/fmm/issues/143#issuecomment-729005624

**Comment by M-Efforts** [comment]
Ok, I just saw that, I need to multiply by 111,000, thank you very much
