### ISSUE TITLE
removed the dependency on gdal.

### ISSUE THREAD

**Issue by machfe522** [cyang-kth/fmm#149]
The gdal  library is too big.  suggest remove GDAL dependent library。

**Comment by cyang-kth** [comment]
The GDAL currently is only used for reading network shapefile. It could be replaced with third party source codes such as shapelib https://github.com/OSGeo/shapelib.  

The OSM file support is also kinds of introducing extra complexity to the project, as the raw OSM file has issues of #99. It should also be possible to remove that. 

However, I will not have time to work on it so I label it as calling for contribution.

**Comment by cyang-kth** [comment]
Dependency on OSM is removed in this commit #154

**Comment by cyang-kth** [comment]
This feature is not urgent, so it is closed.
