### ISSUE TITLE
C++ API Documentation  

### ISSUE THREAD

**Issue by brunoeducsantos** [cyang-kth/fmm#153]
Hi @cyang-kth,

Thanks for the awesome project.

I wonder if there is any documentation about C++ API usage. From the installation is generated sharable object, but I can't access the libraries.

Thanks.

Regards,

Bruno

**Comment by cyang-kth** [comment]
You may refer to this link for using fmm in an external project with cmake (please pull the latest version which will install headers of fmm). 

https://github.com/cyang-kth/fmm/tree/master/example/cpp-api

The C++ API could be found at 
https://cyang-kth.github.io/fmm/

**Comment by cyang-kth** [comment]
Another way could be placing your source code under src the same folder and modify the cmakelists.txt file like the following lines.

Just add one extra line with your cpp file and link it with the FMMLIB library. 

https://github.com/cyang-kth/fmm/blob/cdcda9a9ba4fc103ed217f73fbd7acce176f1ee1/CMakeLists.txt#L134-L147

**Comment by brunoeducsantos** [comment]
Thanks a lot @cyang-kth  for your quick help. I rather use as an external library to be more modular.
Thanks again.

**Comment by brunoeducsantos** [comment]
@cyang-kth I am getting the following error when trying the `cpp-example` :
```
CMake Error at /usr/local/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
Could NOT find FMM (missing: FMM_LIBRARY)

```
PS:
I installed and pulled the new version you provided.
