### ISSUE TITLE
Error When Building on Mac Envoirnment

### ISSUE THREAD

**Issue by MustaphaAhmedALy** [cyang-kth/fmm#162]
Hello  , 

I am facing this errors when attemtting "make j-4 command"

/usr/local/include/boost/geometry/core/coordinate_dimension.hpp:101:23: error: constexpr function's return type 'void' is not a literal type
constexpr inline void assert_dimension()
                      ^
/usr/local/include/boost/geometry/core/coordinate_dimension.hpp:111:23: error: constexpr function's return type 'void' is not a literal type
constexpr inline void assert_dimension_less_equal()
                      ^
/usr/local/include/boost/geometry/core/coordinate_dimension.hpp:117:23: error: constexpr function's return type 'void' is not a literal type
constexpr inline void assert_dimension_greater_equal()

any ideas ?

**Comment by cyang-kth** [comment]
You can compare you cmake and make command output with this log 
https://travis-ci.org/github/cyang-kth/fmm/jobs/750831611
