### ISSUE TITLE
Sample of wiki is not working

### ISSUE THREAD

**Issue by mapperosm** [cyang-kth/fmm#168]
Hello,

I wanted to test the library to mapmatch csv coordinates onto a downloaded OSM-map as described here:
https://fmm-wiki.github.io/docs/tutorial/work-with-osm-data.html

By executing stmatch --network Stockholm.osm.pbf --gps traj.csv -k 16 -r 0.005 -e 0.0005 --vmax 0.0002 --output mr.txt

I receive following error:
[critical][network_config.cpp:65 ] Network format not recognized Stockholm.osm.pbf

Thank you very much for your help.

**Comment by cyang-kth** [comment]
That page is out of date. Working with raw OSM data has this issue https://github.com/cyang-kth/fmm/issues/99

You are recommended to refer to the osm map matching repo to download OSM road network.
