### ISSUE TITLE
Error: Segementation fault: 11 on macOS

### ISSUE THREAD

**Issue by YuanLianggg** [cyang-kth/fmm#169]
After installing fmm on my mac, I ran fmm_test.py in bush to test it. But the error "Segementation fault: 11" occured. Then I run the notebook example, the kernel crashed too.

**Comment by cyang-kth** [comment]
Make sure yoj download the latest version and have the same Python version found in cmake and in the terminal.

**Comment by YuanLianggg** [comment]
> Make sure you download the latest version and have the same Python version found in cmake and in the terminal.

Thanks, I think it might be the problem of Python version (mine is 3.7). I try to use command line, it works.
