### ISSUE TITLE
Working on CSV point file with timestamp

### ISSUE THREAD

**Issue by Mohammed-9089** [cyang-kth/fmm#172]
Hi, I'm working on CSV point file of (Xi'an city), which prepared as required containing (id, x, y, and timestamp) separated by ";" as the follows:
id;x;y;timestamp
8919;108.99553;34.27859;1539041301
8919;108.99552;34.27822;1539041304
8919;108.99552;34.27786;1539041307
8919;108.99552;34.27748;1539041310
8919;108.99551;34.27708;1539041313

So, I wanted to map-match a CSV point file via the following commands: 
Input_config as :
input_config = GPSConfig()
input_config.file = '...../File_with_id.csv'
input_config.id   = "id"
input_config.x    = "x"
input_config.y    = "y"
input_config.timestamp = "timestamp"

print input_config.to_string()

gps file :...... /File_with_id.csv
id column : id
geom column : geom
timestamp column : timestamp
x column : x
y column : y
GPS point : false

Then:
status = model.match_gps_file(input_config, result_config, fmm_config)
But I got the following error:
RuntimeError: Id id or Geometry column geom not found
Please can you tell me how can I fix this problem? @cyang-kth 
Note: every time I get this (GPS point : false), is there any  problem with this. Thanks in advance......!!!

**Comment by cyang-kth** [comment]
Try 

```python
input_config.gps_point = true
```

**Comment by Mohammed-9089** [comment]
Yes it work fine, Thank you very much...... :100:
