### ISSUE TITLE
Any problem in map matching with accuracy

### ISSUE THREAD

**Issue by cyang-kth** [cyang-kth/fmm#18]
If you discovered any problem in map matching related with accuracy where the algorithm fails, you are welcome to report it here. I am also trying to make the algorithm more robust to noises in practice.

**Comment by huangJianwei1119** [comment]
Hi, I am sorry to reply so late. 
The problem could be fixed by rebuilding a comprehensive network.

**Comment by Sean0719** [comment]
Hi, I have one high frequent GPS data, when i do matching, the results are not very good. The matching results are not continuous edges (i try many config parameters). So could you give me some help?

**Comment by cyang-kth** [comment]
@Sean0719 
Could you send me some example data set e.g., the road network and sample GPS data. I guess the problem could be the network topology is incomplete or there are some special type of noisy observations. 
My email is cyang (at) kth.se

**Comment by Sean0719** [comment]
Hi, I already sent it. Thank you very much.

**Comment by cyang-kth** [comment]
@Sean0719 

I think the problem is that the topology of your network is incomplete. Some edges have the wrong direction. 

The `mr.txt` file contains a field o_path, which is the edge matched for each point in the trajectory. But its complete path is missing, which implies that **these matched edges in the o_path cannot be connected**.

One example is shown below. Green is the original trajectory and blue is the edges matched. 

![screenshot from 2019-03-08 10-17-12](https://user-images.githubusercontent.com/6810084/54019386-5bec8e80-418b-11e9-80db-7efbb9eec809.png)

As you can see, some edges are matched in a weird manner. The reason is that some edges have the wrong direction, or should be two way (The orange color below shows the road network). 

![screenshot from 2019-03-08 10-25-36](https://user-images.githubusercontent.com/6810084/54019844-8d198e80-418c-11e9-8b47-fd1bc2ebc9ce.png)

I find that the osm network contains a one-way attribute, which is false for most of these links except some primary road. One solution isto create a reversed link for each of the edges whose one-way is false. 

You may refer to this issue https://github.com/cyang-kth/fmm/issues/18, which contains some postgresql codes for creating a reversed road network in a spatial database.
