### ISSUE TITLE
Cmake error when building images with dockerfile in repo

### ISSUE THREAD

**Issue by vonfeng** [cyang-kth/fmm#182]
**Describe the bug**
When I use the dockerfile in repo to build image, following issue happens
`CMake Error: The source directory "/fmm" does not appear to contain CMakeLists.txt.`

**Screenshots**
![image](https://user-images.githubusercontent.com/11694233/109022122-7ca2ab80-76f6-11eb-95c4-b1c5f870948e.png)

**Comment by TkMurakami** [comment]
I am facing the same issue and haven't been able to resolve it. If you remember how you solved it, could you please share?
<img width="892" alt="スクリーンショット 2024-08-02 17 42 29" src="https://github.com/user-attachments/assets/7d7913f5-20b5-493e-849f-367aa46248c2">
