### ISSUE TITLE
Not able to run on osm data

### ISSUE THREAD

**Issue by cvmlddev** [cyang-kth/fmm#184]
**Note**
Before posting an issue about bug in the program
- Make sure you have downloaded/pulled the **latest version** of repo
- **search the GitHub [issue page](https://github.com/cyang-kth/fmm/issues)** with keywords to check if a similar issue has been posted or not. 

**Describe the bug**
The documentation mentions that fmm can now process osm files as well.
I downloaded osm.pbf file https://download.geofabrik.de/index.html.

Following the documentation I ran
`stmatch --network custom.osm.pbf --gps custom.csv -k 16 -r 0.005 -e 0.0005 --vmax 0.0002 --output mr.txt
`
It gives the error
**[critical][network_config.cpp:65 ] Network format not recognized india.osm.pbf**

**Expected behavior**
It should be able to process OSM files as well
**Screenshots**

**Comment by ziXet** [comment]
You should follow this Tutorial:
https://github.com/cyang-kth/osm_mapmatching

I think you no longer will be able to use osm .pbf file directly. 

If you follow the tutorial, you'll see the for osm maps, it uses osmnx to download the graph.

**Comment by cyang-kth** [comment]
The reason for removing the support of osm file is that it generally contains topology issues as described here 
https://github.com/cyang-kth/fmm/issues/99.

**Comment by cvmlddev** [comment]
Would it work if we convert osm to shapeFile format?(.osm -> .geojson -> .shp)

**Comment by cyang-kth** [comment]
No, you have to use some advanced tool to build the topology like osmnx, other conversion only stores the data in a different format so it won't work.
