### ISSUE TITLE
Saving ubodt file

### ISSUE THREAD

**Issue by Vedanta-Z** [cyang-kth/fmm#187]
**Is your feature request related to a problem? Please describe.**
Would it be possible to save the read UBODT file?
So, everytime that fmm is run , UBODT is not read again.
Currently, Even if I save precomputed ubodxt file, It takes around a minute to read the ubodxt file for a dense city map.

**Describe the solution you'd like**
Something like saving UBODT in a file, then loading it and running fmm.

**Comment by cyang-kth** [comment]
The UBODT file is already stored in a file. You can try binary format to improve the reading speed. Alternatively, you can try to use the python API which allows you to read the ubodt just once and try different settings. 

https://github.com/cyang-kth/fmm/blob/master/example/notebook/fmm_example.ipynb
