### ISSUE TITLE
About fmm with timestamps as result.

### ISSUE THREAD

**Issue by Hongjun-Wang** [cyang-kth/fmm#188]
I want to be able to save 'timestamp' as a result when used fmm and I see that you have the example input config with timestamp. Could you please tell me how to save the 'timestamp' as the result?

**Comment by cyang-kth** [comment]
Currently, there is no option to save the timestamp. The timestamp is used as an input information. You can try to associate the timestamp with the result perhaps in Python.

**Comment by Hongjun-Wang** [comment]
Ok, thanks! I will try it.
