### ISSUE TITLE
How is cpath made from opath?

### ISSUE THREAD

**Issue by paymonnb** [cyang-kth/fmm#190]
How is cpath made from opath?

I visualized opath and cpath using each path edge's start node.
Since I need the connected nodes list(not separated from previous node), I supposed to use cpath. 
However cpath seems much unrealistic than opath.
Is there any method to improve cpath to be more realistic or make opath to be connected?

opath
<img width="192" alt="opath" src="https://user-images.githubusercontent.com/83068124/115964629-5e272800-a560-11eb-801b-384a2fcd8f65.PNG">

cpath
<img width="199" alt="cpath" src="https://user-images.githubusercontent.com/83068124/115964656-7bf48d00-a560-11eb-8d2e-0218432af16b.PNG">

**Comment by cyang-kth** [comment]
You can check the illustration here 

https://fmm-wiki.github.io/docs/documentation/output/

![image](https://user-images.githubusercontent.com/6810084/115977296-3d36f500-a5a9-11eb-9bc1-14ed5c3b0ef2.png)

The cpath is created by connecting the opath. The reason you see unrealistic path could be your network contains topology errors and some edges are misconnected.

**Comment by paymonnb** [comment]
Thank you for your answer.

I downloaded my network based on your 'download_network' code in osmnx_example.

```
bounds = (126.733235, 126.789141, 37.480174, 37.512656)
x1,x2,y1,y2 = bounds
boundary_polygon = Polygon([(x1,y1),(x2,y1),(x2,y2),(x1,y2)])
G = ox.graph_from_polygon(boundary_polygon, network_type='all_private',simplify=False)
start_time = time.time()
save_graph_shapefile_directional(G, filepath='./network')
print("--- %s seconds ---" % (time.time() - start_time))
```

I set the network_type to 'all_private'. Is there any problem in my code above?

**Comment by paymonnb** [comment]
I think cpath has mulitple path like this picture.
Original gps data is similar with line above. 

<img width="354" alt="multiple cpath" src="https://user-images.githubusercontent.com/83068124/115986283-73489900-a5ea-11eb-89eb-a6e9625d16d7.PNG">

**Comment by cyang-kth** [comment]
I think at the intersection, the lines are not connected correctly.
