### ISSUE TITLE
Use fmm to snap coordinate to nearest road

### ISSUE THREAD

**Issue by Vedanta-Z** [cyang-kth/fmm#193]
**Is your feature request related to a problem? Please describe.**
I would like to snap a coordinate to closest osm road. 

**Describe the solution you'd like**
I tried snapping a single coordinate, but did not get an output.
Can we make some changes to allow fmm to snap a single coordinate?

**Additional context**
Snapping a single coordinate with a given (lat,lon) to the closest osm road.

**Comment by cyang-kth** [comment]
Snapping to the closest road may not give the correct matching result, or you could try with the configuration of k=1.
