### ISSUE TITLE
TypeError: can't pickle SwigPyObject objects

### ISSUE THREAD

**Issue by mchl0203** [cyang-kth/fmm#194]
If I use python multiprocessing to run STMATCH, it will get an error: TypeError: can't pickle SwigPyObject objects.
Does anyone encounter this problem, and how to deal with it?

**Comment by cyang-kth** [comment]
The python binding is created using swig, which may not work with multiprocessing in Python. 

To run parallelly, try with the option `use_omp=True`

```python
status = fmm_model.match_gps_file(input_config, result_config, fmm_config, use_omp = True)
print status
```
