### ISSUE TITLE
UBODT precomputation problem with large network

### ISSUE THREAD

**Issue by cyang-kth** [cyang-kth/fmm#2]
When the graph is small but one node in it is extremely large, e.g., 300000, a large graph is created with that 300000 number of nodes where the iteration in `ubodt_gen` checks the entire graph.

**Comment by cyang-kth** [comment]
The labeled graph in BGL might be a solution:
http://www.boost.org/doc/libs/1_46_1/libs/graph/example/labeled_graph.cpp

**Comment by skinkie** [comment]
```
Id column WVK_ID
	Number of edges in file: 1023122
	SHP ID idx: 0
	SHP source idx: 2
	SHP target idx: 3
	Warning: srid is not found, set to 4326 for default
	SRID is 28992
Read network finish.
	The maximum node ID is 556557004
	Total number of edges read 1023122
Construct graph from network edges start
Network edges :1023122 
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```
I assume the same cause is the result for this.

**Comment by skinkie** [comment]
After renumbering:

```
------------ Fast map matching (FMM) ------------
------------     Author: Can Yang    ------------
------------   Version: 2017.11.11   ------------
------------  Applicaton: ubodt_gen  ------------
Read configuration from xml file: ubodt_config.xml
Validating configuration for RODT construction:
    Warning, overwrite existing result file.ubodt.txt
Validating success.
Write UBODT to file wegvakken_renumbered.shp
Read network shp file from wegvakken_renumbered.shp
Id column WVK_ID
	Number of edges in file: 1019233
	SHP ID idx: 2
	SHP source idx: 0
	SHP target idx: 1
	SRID is 4326
Read network finish.
	The maximum node ID is 743142
	Total number of edges read 1019233
Construct graph from network edges start
Network edges :1019233 
Graph nodes 743143
Construct graph from network edges end
Start to generate UBODT with delta 3
Progress source 0
Progress source 5000
```
But it is _very_ slow. I think in principle I understand what you did from the paper, and implemented something similar based on https://github.com/RoutingKit/RoutingKit as backend.

**Comment by cyang-kth** [comment]
Thank you for your comments. 

The network I tested is much smaller (1/30) than yours. I am not sure if that can be optimized or not.
My implementation of routing based on Boost graph library is primarily based on pgRouting https://github.com/pgRouting/pgrouting where no spatial information is used. 

Is your network a private one or converted from OSM? I am also looking forward to testing it with some large network.

**Comment by skinkie** [comment]
@cyang-kth very public and open data :-)
http://geodata.nationaalgeoregister.nl/nwbwegen/extract/nwbwegen.zip

I actually wanted to test a much larger network ;-)

**Comment by cyang-kth** [comment]
@skinkie I have just tested with the nwbwegen network with renumbered ID and encountered the same problem.

I think the bottleneck may be these two lines in the driving_distance function
https://github.com/cyang-kth/fmm/blob/master/src/network_graph.hpp#L159
https://github.com/cyang-kth/fmm/blob/master/src/network_graph.hpp#L159

For each source node, it will create a distance map and predecessor map covering the total number of vertices in the graph as it does not know how many nodes will be visited in advance. 

For a large network,  the overhead can be problematic. Perhaps a spatial index can be used in this case to constrain the searching to a small area.

**Comment by skinkie** [comment]
My use case for testing FMM is to map match a complete country with another dataset of the country. Would it be doable to implement a maximum distance from a point?

**Comment by cyang-kth** [comment]
In FMM, there is a maximum distance defined by **delta** in the ubodt configuration file.
https://github.com/cyang-kth/fmm#configuration-of-ubodt_gen
ubodt_config->parameters->delta
which is the upper bound of UBODT. 

However, inside the driving distance function, the maximum distance is considered but in a less intelligent way. Namely, the maximum distance is used to terminate the searching earlier but it is initialized with two large vectors to record the distances and predecessors for all nodes in the graph. There should be a more efficient way to do this. I will check if Boost graph library provides any other interfaces.

**Comment by skinkie** [comment]
I killed it, but these sizes are unsustainable ;)
```-rw-r--r-- 1 skinkie skinkie 164G Mar  8 16:54 ubodt.txt```

**Comment by cyang-kth** [comment]
@skinkie 
I have just created an optimized version of the precomputation app by solving the bottleneck of wasted initialization, which significantly outperforms current implementation.  

Now I tested with delta = 1000m on your network and it takes
**3min27.524s** to generate a UBODT with **19,022,620 rows** and occupies **766MB** space. 

```
------------ Fast map matching (FMM) ------------
------------     Author: Can Yang    ------------
------------   Version: 2017.11.11   ------------
------------Application: ubodt_gen_opt------------
Read configuration from xml file: ubodt_config.xml
Validating configuration for UBODT construction:
Validating success.
Write UBODT to file wegvakken_renumber.shp
Read network shp file from wegvakken_renumber.shp
Id column WVK_ID
	Number of edges in file: 1023122
	SHP ID idx: 0
	SHP source idx: 1
	SHP target idx: 2
	SRID is 4289
Read network finish.
	The maximum node ID is 746418
	Total number of edges read 1023122
Construct graph from network edges start
Network edges :1023122 
Graph nodes 746419
Construct graph from network edges end
Start to generate UBODT with delta 1000
Progress source 0
...
Progress source 745000
Time takes 204.392
Cleaning network
Cleaning network finished
------------    Program finished     ------------

real	3m27.524s
user	3m23.167s
sys	0m1.596s

```
I will upload the codes to the repo soon. 
You mentioned that 164GB file is generated. Which delta did you choose?

**Comment by cyang-kth** [comment]
With 3000 meters delta, the statistics are 
4m32.978s generates 79998367 rows occupies 3,2G.

**Comment by skinkie** [comment]
```
<?xml version="1.0" encoding="utf-8"?>
<ubodt_config>
    <input>
        <network>
            <file>wegvakken_renumbered.shp</file>
            <id>WVK_ID</id>
            <source>JTE_ID_BEG</source>
            <target>JTE_ID_END</target>
        </network>
    </input>
    <parameters>
        <delta>3</delta>
    </parameters>
    <output>
        <file>ubodt.txt</file>
    </output>
</ubodt_config>
```
...so if my delta was 3, where did it go wrong ;)

**Comment by cyang-kth** [comment]
I have uploaded the optimized code, now you should be able to install the `ubodt_gen_opt` app with `make;make install`and run it on your network. Could it be the ID of your source and target column? Did you also update them after renumbering?

**Comment by skinkie** [comment]
I exported a new shp from PostGIS after renumbering. So all columns 
retained the same name.

**Comment by skinkie** [comment]
Could you paste your config too?

**Comment by cyang-kth** [comment]
```
<?xml version="1.0" encoding="utf-8"?>
<ubodt_config>
    <input>
        <network>
            <file>wegvakken_renumber.shp</file>
            <id>WVK_ID</id>
            <source>SOURCE</source>
            <target>TARGET</target>
        </network>
    </input>
    <parameters>
        <delta>3000</delta>
    </parameters>
    <output>
        <file>ubodt3000.txt</file>
    </output>
</ubodt_config>
```
I have renamed the source and target columns when exporting from PostGIS database. I think the problem may lie in the shapefile.

Here is the meta information of shapefile. by run `ogrinfo wegvakken_renumber.shp -so -al`

```
INFO: Open of `wegvakken_renumber.shp'
      using driver `ESRI Shapefile' successful.

Layer name: wegvakken_renumber
Geometry: Line String
Feature Count: 1023122
Extent: (13592.698000, 306956.000000) - (278022.270000, 617955.000000)
Layer SRS WKT:
PROJCS["Amersfoort / RD New",
    GEOGCS["Amersfoort",
        DATUM["Amersfoort",
            SPHEROID["Bessel 1841",6377397.155,299.1528128,
                AUTHORITY["EPSG","7004"]],
            TOWGS84[565.4171,50.3319,465.5524,-0.398957,0.343988,-1.87740,4.0725],
            AUTHORITY["EPSG","6289"]],
        PRIMEM["Greenwich",0,
            AUTHORITY["EPSG","8901"]],
        UNIT["degree",0.0174532925199433,
            AUTHORITY["EPSG","9122"]],
        AUTHORITY["EPSG","4289"]],
    PROJECTION["Oblique_Stereographic"],
    PARAMETER["latitude_of_origin",52.15616055555555],
    PARAMETER["central_meridian",5.38763888888889],
    PARAMETER["scale_factor",0.9999079],
    PARAMETER["false_easting",155000],
    PARAMETER["false_northing",463000],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]],
    AXIS["X",EAST],
    AXIS["Y",NORTH],
    AUTHORITY["EPSG","28992"]]
WVK_ID: Real (32.10)
SOURCE: Integer64 (11.0)
TARGET: Integer64 (11.0)

```
Some features are (by run `ogrinfo wegvakken_renumber.shp -al -fid 2`)
```
OGRFeature(wegvakken_renumber):1
  WVK_ID (Real) = 27142019.0000000000
  SOURCE (Integer64) = 1
  TARGET (Integer64) = 11
  LINESTRING (13942.077 371449.753,13948.956 371443.555,13962.4750000015 371429.184,13976.522 371415.077,13982.55 371409.6)
OGRFeature(wegvakken_renumber):2
  WVK_ID (Real) = 30141037.0000000000
  SOURCE (Integer64) = 75
  TARGET (Integer64) = 82
  LINESTRING (15381 370713,15390 370716,15405 370722)
```

**Comment by skinkie** [comment]
```
Layer name: wegvakken_renumbered
Geometry: Line String
Feature Count: 1019233
Extent: (3.358783, 50.751345) - (7.227445, 53.541816)
Layer SRS WKT:
GEOGCS["WGS 84",
    DATUM["WGS_1984",
        SPHEROID["WGS 84",6378137,298.257223563,
            AUTHORITY["EPSG","7030"]],
        AUTHORITY["EPSG","6326"]],
    PRIMEM["Greenwich",0,
        AUTHORITY["EPSG","8901"]],
    UNIT["degree",0.0174532925199433,
        AUTHORITY["EPSG","9122"]],
    AUTHORITY["EPSG","4326"]]
JTE_ID_BEG: Real (19.0)
JTE_ID_END: Real (19.0)
WVK_ID: Real (19.0)
```

**Comment by cyang-kth** [comment]
I think the reason is your reference system.

Each degree of latitude is approximately 69 miles (111 kilometers) apart.
In WGS84 whose unit is degree, a delta of 3 equals to Euclidean distance of 333 km, which is too large. 

In my test, I used the projected network whose unit is meter, therefore, the delta I tested is much smaller than yours. 

Note that, in fmm,  **no geographic transformation is performed**.

**Comment by skinkie** [comment]
Ah so you did the 28992 and I _did_ a nice transformation :-) I'll do another test then.

**Comment by skinkie** [comment]
I really wonder what kind of CPU you are generating the file within 5 minutes since proces is CPU bound. Currently using a Intel(R) Xeon(R) CPU D-1531 @ 2.20GHz

**Comment by cyang-kth** [comment]
The CPU I am currently using is Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz

**Comment by skinkie** [comment]
```
Progress source 740000
Time takes 3012.85
Cleaning network
Cleaning network finished
------------    Program finished     ------------
```
This is a big difference ;)

**Comment by cyang-kth** [comment]
Which delta did you use? That is really strange, the network we used is in almost the same. Did you renumber the ID of source and target?

**Comment by cyang-kth** [comment]
Which app did you run? I have created an optimized app called `ubodt_gen_opt`
Please try
```
make
make install
ubodt_gen_opt ubodt_config.xml
```

**Comment by skinkie** [comment]
Ah! That might explain the difference, I didn't use the _opt version. I'll report back the improvement :)

**Comment by skinkie** [comment]
```
Time takes 368.169
Cleaning network
Cleaning network finished
```
Far mor reasonable :)
```
md5sum ubodt.txt
5ac8dcce1f37cb2930243b79523c254d  ubodt.txt
md5sum ubodt.txt-noopt
5ac8dcce1f37cb2930243b79523c254d  ubodt.txt-noopt
```

**Comment by skinkie** [comment]
Do you now also handle the fact that node ids don't have to be a continuous sequence?

**Comment by cyang-kth** [comment]
I am also thinking about this. One solution would be to store the discontinuous node ID as the vertex property and maintain a hash map to record the index of nodes incrementally during the graph creation. I may cost extra processing time but I think it worths.

**Comment by cyang-kth** [comment]
@skinkie 
I have implemented the support for discontinuous node ID in the network. The UBODT now stores node ID and edge index in each row.   

The performance compared with the renumbered shapefile 
delta:1000m, running time 207s (renumbered) to 241s (original), file size 766MB to 993MB
delta:3000m, 272s to 355s, file size 3.2GB to 4.1GB

Besides,  `ubodt_gen_opt` is replaced with `ubodt_gen` in the project.
