### ISSUE TITLE
How can we improve inference time?

### ISSUE THREAD

**Issue by Vedanta-Z** [cyang-kth/fmm#200]
I am using STMATCH for matching GPS pings on a large city map.
I am converting the map from osm using osmnx graph_from_xml function.

The results look good. I am using the following configuration:
```
       config.k = 7
       config.gps_error = 0.5
       config.radius = 0.4
       config.vmax = 30
       config.factor = 1.5
       config.reverse_tolerance = 1.0

```

I am using the Python wrapper, taking the input in wkt format , and matching using match_wkt function.

The inference time for some trips with moderate number of pings(Around 250 pings) exceeds 5 seconds. 
What can we do to bring the inference time down?

**Comment by cyang-kth** [comment]
You could use the fmm algorithm instead of the stmatch.
