### ISSUE TITLE
Inferring travel time between points in resulting geometry

### ISSUE THREAD

**Issue by kodonnell** [cyang-kth/fmm#209]
**Is your feature request related to a problem? Please describe.**
Say I have three points I want to match: A at 10:01am, B at 10:02am, and C and 10:03am. Say the map-matched path/geometry is a line of 10 points - what I want to do is infer the time at each point e.g. was the time for the 5th point 10:02.05am or 10:02:59am etc. The main problem with trying to do this manually myself is I don't think I can associate each of my three input points to the one of the 10 points e.g. I don't know if point B was matched to the 2nd or 9th point etc., and hence can't infer times myself (by calculating distance etc.)

**Describe the solution you'd like**
In python, either:
- Built in support for doing this so that e.g. if a Trajectory is provided, the timestamps are also inferred. However, this may be messy as inferring time depends on speed limits etc.
- Something similar to `result.indices` but which points to the index of the point in the resulting geometry of points, not edges. Then I could work backward myself as outlined above. Having access to more point/line metadata may help too (e.g. OSM speeds etc.).

**Describe alternatives you've considered**
I could manually reconstruct graphs myself, but that's pretty icky! I've had a look around and search but didn't seem to see anything solving this - apologies if I missed it!

**Additional context**
Ultimately, it's for pretty animations of routes, which requires knowing the time at each point.

**Comment by cyang-kth** [comment]
I think currently there is no direct support for this. Maybe you could try to use the Python API to do some post-processing.
