### ISSUE TITLE
FMM Mode Implemented for long-distance routing queries

### ISSUE THREAD

**Issue by elmiraberjisian** [cyang-kth/fmm#22]
In your paper in section 4.2.4 you mentioned four modes of FMM that affect the accuracy and performance of the algorithm (modes are: brute force, optimized, UBODT, Dijkstra). Which mode was implemented in the source code? Is it possible to set it as optimized mode?

Thank you!

**Comment by cyang-kth** [comment]
@elmiraberjisian 
In this project, the source code provided corresponds to the mode UBODT, which only queries the table and if finally it cannot find a complete path then the trajectory is unmatched. The justification is that long distance gap of gps observations is unlikely to provide information with high confidence.

The codes of another mode UBODT+Dijkstra is also provided here 
https://github.com/cyang-kth/fmm/tree/master/dev/adv_mode
