### ISSUE TITLE
one trajectory not matching

### ISSUE THREAD

**Issue by rvxfahim** [cyang-kth/fmm#221]
I am unable to match one trajectory which looks fine in QGIS over the shapefile in QGIS. Can you please suggest how to match this?

The zip file includes the shapefile and multiple trajectory file and also a single trajectory file.

Here is the screenshot of the result with the single trajectory csv.
![image](https://user-images.githubusercontent.com/32749520/139334897-7b601727-c494-4ac7-b912-ed197d6f3f28.png)

[https://mega.nz/file/r8lzCYjY#mejwfdowMc4r9lr4D_rx1X0pPglY6EteKXwQZoBfPNM](url)
Thanks.

**Comment by cyang-kth** [comment]
Please refer to the original paper or docs for your question.

**Comment by ziXet** [comment]
> I tried most combination. Only didn't try to change delta value. Can you tell me what does delta value mean, and how to choose the value if network is very large?
The easiest way to calculate the best value for the delta is the following.
1. find the maximum time different between two consecutive points in your trajectory. (e.g. 5 seconds)
2. find the maximum speed of the object (e.g 120km/h ~ 33m/s)
3. multiply those numbers (e.g. 5*33=165m ~ 0.001 deg/s = delta)

Hope this hepled.
