### ISSUE TITLE
Installation with Anaconda

### ISSUE THREAD

**Issue by changfyg** [cyang-kth/fmm#222]
Hi.
I think I installed successfully fmm using the instructions on https://fmm-wiki.github.io/docs/installation/windows.html
Am able to run from cygwin:
$ python fmm_test.py
[info] [network.cpp:72] Read network from file ../data/edges.shp ....
...WKT  LINESTRING(0.20081215 2,1 2,2 2,3 2,3 3,4 3,4 2.6233757)

Next on a jupyter notebook, run:
from fmm import FastMapMatch, Network, NetworkGraph, UBODTGenAlgorithm, UBODT, FastMapMatchConfig

Notebook returned:
ModuleNotFoundError: No module named 'fmm'

Need some pointers on how to resolve this.
Thanks

**Comment by cyang-kth** [comment]
If you are using anaconda, it has not been tested on Windows platform. I suggest you try a Ubuntu OS which would be easier.

**Comment by changfyg** [comment]
Thank you for your advice.
Yes. It is deployed using Anaconda on Windows 10.
I guess this can be a feature request.
