### ISSUE TITLE
No matching results when having points out of map

### ISSUE THREAD

**Issue by yxnchen** [cyang-kth/fmm#223]
Hi, I am using fmm to conduct some map matching work on taxi GPS data. My task is to match the GPS data to a specific area (smaller than the whole cover of the GPS data). However, no matching path is returned when having points out of the map although some points is well fit to the edges (see the first figure). If I truncate the GPS data (see the second figure), fmm does well.

Is it possible to add this feature to fmm in the future? That is, if some points are out of the map, we can still get the matched path from the points inside of the map.

![f1](https://user-images.githubusercontent.com/8400698/142987822-146973fc-0853-45d5-bcd1-b028c5136891.png)
![f2](https://user-images.githubusercontent.com/8400698/142987878-5c2d3e2d-1f97-40f3-b083-9d2a219877d4.png)

**Comment by yxnchen** [comment]
Even 'opath' is empty.

**Comment by cyang-kth** [comment]
That phenomenon is expected because when there are no edges near some of these GPS points, there will be no paths inferred for these trajectories. It will not export anything if some points cannot be matched.
