### ISSUE TITLE
speed is always 0

### ISSUE THREAD

**Issue by kfyidrig** [cyang-kth/fmm#229]
**Describe the bug**
In the results output using fmm or stmatch, the speed is always 0. Is the speed output by subtracting of longitude and latitude？I think the speed unit should be kilometers per second or something.
在运行fmm或者stmatch算法后，输出的结果中速度一直为0，速度是经纬度变化做减法得出的吗？我认为速度单位应该是千米每秒之类的。

**Expected behavior**

Get the average speed of each interval, in km / s or something.
得到每个间隔的平均速度，单位为km每秒等等

**Screenshots**
output
程序输出结果
![speed](https://user-images.githubusercontent.com/13808186/145805614-05c564e3-47e3-43ee-9f02-f467b15a7345.png)

dataset
我的数据集
![dataset](https://user-images.githubusercontent.com/13808186/145806389-209fc302-91b0-4dd2-8729-068357e0eaab.png)

command arguments
命令参数
![command](https://user-images.githubusercontent.com/13808186/145807445-540c7d99-460f-4376-ac92-d32c7f9d1aac.png)

**Comment by cyang-kth** [comment]
你的数据包含很多的静止点，移动距离为0，所以速度为0.

**Comment by kfyidrig** [comment]
> 你的数据包含很多的静止点，移动距离为0，所以速度为0.

感谢，但是前面几组数据似乎速度不应该为0，我在尝试运行更多数据集，看看速度是否为0，可以请问下速度的单位是什么吗？

**Comment by kfyidrig** [comment]
> 你的数据包含很多的静止点，移动距离为0，所以速度为0.
我更换了数据集，但是速度依然全部为0
![new test](https://user-images.githubusercontent.com/13808186/145817156-8467bc46-700b-43ac-b2ed-f40e9deb1da3.png)

**Comment by cyang-kth** [comment]
可能是精度的原因，可以试试输出spdist来看看结果，可能是临近的点都匹配到端点上了，建议你需要对gps可视化看一下具体位置。

**Comment by kfyidrig** [comment]
> 可能是精度的原因，可以试试输出spdist来看看结果，可能是临近的点都匹配到端点上了，建议你需要对gps可视化看一下具体位置。

最短路径确实趋近于0
![spdist](https://user-images.githubusercontent.com/13808186/145828117-23c97239-82ad-4f68-ba1e-9b29ce95c702.png)

这是可视化结果
![vis](https://user-images.githubusercontent.com/13808186/145828212-8c19aeae-ef9f-4bc5-beb6-3e32711d68b3.png)

以下是计算的速度
```python
import pandas as pd
```


```python
import transbigdata as tbd
```


```python
# 读入GPS数据
data=pd.read_csv('./part_data.csv',sep=';')
```


```python
data.tail(4)
```




<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>id</th>
      <th>x</th>
      <th>y</th>
      <th>timestamp</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>26</th>
      <td>0</td>
      <td>104.059228</td>
      <td>30.504364</td>
      <td>1525170801</td>
    </tr>
    <tr>
      <th>27</th>
      <td>0</td>
      <td>104.059088</td>
      <td>30.504385</td>
      <td>1525170804</td>
    </tr>
    <tr>
      <th>28</th>
      <td>0</td>
      <td>104.059058</td>
      <td>30.504385</td>
      <td>1525170806</td>
    </tr>
    <tr>
      <th>29</th>
      <td>0</td>
      <td>104.059038</td>
      <td>30.504385</td>
      <td>1525170808</td>
    </tr>
  </tbody>
</table>
</div>




```python
# 创建新的df，用于错位存储经纬度
pointPair=pd.DataFrame()
```


```python
pointPair['Lng1']=data.iloc[:-1,1:2]
pointPair['Lat1']=data.iloc[:-1,2:3]
pointPair['Lng2']=data.iloc[1:,1:2].reset_index(drop=True)
pointPair['Lat2']=data.iloc[1:,2:3].reset_index(drop=True)
```


```python
pointPair.head(4)
```




<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Lng1</th>
      <th>Lat1</th>
      <th>Lng2</th>
      <th>Lat2</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>104.061074</td>
      <td>30.502242</td>
      <td>104.061144</td>
      <td>30.502372</td>
    </tr>
    <tr>
      <th>1</th>
      <td>104.061144</td>
      <td>30.502372</td>
      <td>104.061244</td>
      <td>30.502602</td>
    </tr>
    <tr>
      <th>2</th>
      <td>104.061244</td>
      <td>30.502602</td>
      <td>104.061294</td>
      <td>30.502732</td>
    </tr>
    <tr>
      <th>3</th>
      <td>104.061294</td>
      <td>30.502732</td>
      <td>104.061313</td>
      <td>30.502772</td>
    </tr>
  </tbody>
</table>
</div>




```python
# 求两点之间的距离
pointPair['Dis']=tbd.getdistance(pointPair['Lng1'],pointPair['Lat1'],pointPair['Lng2'],pointPair['Lat2'])
```


```python
def getSpeed(row):
    return row['Dis'] / 3 * 3.6;
```


```python
pointPair['speed(km/h)']=pointPair.apply(getSpeed,axis=1)
```


```python
# pointPair=pointPair.drop(['speed','speed(km/sh)'],axis=1)
```


```python
pointPair
```




<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Lng1</th>
      <th>Lat1</th>
      <th>Lng2</th>
      <th>Lat2</th>
      <th>Dis</th>
      <th>speed(km/h)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>104.061074</td>
      <td>30.502242</td>
      <td>104.061144</td>
      <td>30.502372</td>
      <td>15.914904</td>
      <td>19.097885</td>
    </tr>
    <tr>
      <th>1</th>
      <td>104.061144</td>
      <td>30.502372</td>
      <td>104.061244</td>
      <td>30.502602</td>
      <td>27.280696</td>
      <td>32.736836</td>
    </tr>
    <tr>
      <th>2</th>
      <td>104.061244</td>
      <td>30.502602</td>
      <td>104.061294</td>
      <td>30.502732</td>
      <td>15.213266</td>
      <td>18.255919</td>
    </tr>
    <tr>
      <th>3</th>
      <td>104.061294</td>
      <td>30.502732</td>
      <td>104.061313</td>
      <td>30.502772</td>
      <td>4.837133</td>
      <td>5.804560</td>
    </tr>
    <tr>
      <th>4</th>
      <td>104.061313</td>
      <td>30.502772</td>
      <td>104.061333</td>
      <td>30.502802</td>
      <td>3.841292</td>
      <td>4.609550</td>
    </tr>
    <tr>
      <th>5</th>
      <td>104.061333</td>
      <td>30.502802</td>
      <td>104.061373</td>
      <td>30.502881</td>
      <td>9.674277</td>
      <td>11.609132</td>
    </tr>
    <tr>
      <th>6</th>
      <td>104.061373</td>
      <td>30.502881</td>
      <td>104.061453</td>
      <td>30.503041</td>
      <td>19.348577</td>
      <td>23.218292</td>
    </tr>
    <tr>
      <th>7</th>
      <td>104.061453</td>
      <td>30.503041</td>
      <td>104.061513</td>
      <td>30.503181</td>
      <td>16.576905</td>
      <td>19.892286</td>
    </tr>
    <tr>
      <th>8</th>
      <td>104.061513</td>
      <td>30.503181</td>
      <td>104.061583</td>
      <td>30.503331</td>
      <td>17.956495</td>
      <td>21.547794</td>
    </tr>
    <tr>
      <th>9</th>
      <td>104.061583</td>
      <td>30.503331</td>
      <td>104.061653</td>
      <td>30.503461</td>
      <td>15.915077</td>
      <td>19.098092</td>
    </tr>
    <tr>
      <th>10</th>
      <td>104.061653</td>
      <td>30.503461</td>
      <td>104.061663</td>
      <td>30.503491</td>
      <td>3.467612</td>
      <td>4.161135</td>
    </tr>
    <tr>
      <th>11</th>
      <td>104.061663</td>
      <td>30.503491</td>
      <td>104.061673</td>
      <td>30.503511</td>
      <td>2.418584</td>
      <td>2.902301</td>
    </tr>
    <tr>
      <th>12</th>
      <td>104.061673</td>
      <td>30.503511</td>
      <td>104.061733</td>
      <td>30.503621</td>
      <td>13.497608</td>
      <td>16.197129</td>
    </tr>
    <tr>
      <th>13</th>
      <td>104.061733</td>
      <td>30.503621</td>
      <td>104.061783</td>
      <td>30.503741</td>
      <td>14.162377</td>
      <td>16.994853</td>
    </tr>
    <tr>
      <th>14</th>
      <td>104.061783</td>
      <td>30.503741</td>
      <td>104.061663</td>
      <td>30.503951</td>
      <td>26.030194</td>
      <td>31.236233</td>
    </tr>
    <tr>
      <th>15</th>
      <td>104.061663</td>
      <td>30.503951</td>
      <td>104.061623</td>
      <td>30.503951</td>
      <td>3.824734</td>
      <td>4.589680</td>
    </tr>
    <tr>
      <th>16</th>
      <td>104.061623</td>
      <td>30.503951</td>
      <td>104.061543</td>
      <td>30.503981</td>
      <td>8.350284</td>
      <td>10.020341</td>
    </tr>
    <tr>
      <th>17</th>
      <td>104.061543</td>
      <td>30.503981</td>
      <td>104.061343</td>
      <td>30.504021</td>
      <td>19.641433</td>
      <td>23.569719</td>
    </tr>
    <tr>
      <th>18</th>
      <td>104.061343</td>
      <td>30.504021</td>
      <td>104.061034</td>
      <td>30.504092</td>
      <td>30.659066</td>
      <td>36.790879</td>
    </tr>
    <tr>
      <th>19</th>
      <td>104.061034</td>
      <td>30.504092</td>
      <td>104.060665</td>
      <td>30.504162</td>
      <td>36.236989</td>
      <td>43.484386</td>
    </tr>
    <tr>
      <th>20</th>
      <td>104.060665</td>
      <td>30.504162</td>
      <td>104.060335</td>
      <td>30.504203</td>
      <td>31.872182</td>
      <td>38.246618</td>
    </tr>
    <tr>
      <th>21</th>
      <td>104.060335</td>
      <td>30.504203</td>
      <td>104.060096</td>
      <td>30.504243</td>
      <td>23.381761</td>
      <td>28.058113</td>
    </tr>
    <tr>
      <th>22</th>
      <td>104.060096</td>
      <td>30.504243</td>
      <td>104.059976</td>
      <td>30.504263</td>
      <td>11.690800</td>
      <td>14.028960</td>
    </tr>
    <tr>
      <th>23</th>
      <td>104.059976</td>
      <td>30.504263</td>
      <td>104.059707</td>
      <td>30.504304</td>
      <td>26.203055</td>
      <td>31.443666</td>
    </tr>
    <tr>
      <th>24</th>
      <td>104.059707</td>
      <td>30.504304</td>
      <td>104.059467</td>
      <td>30.504334</td>
      <td>23.193401</td>
      <td>27.832082</td>
    </tr>
    <tr>
      <th>25</th>
      <td>104.059467</td>
      <td>30.504334</td>
      <td>104.059228</td>
      <td>30.504364</td>
      <td>23.193176</td>
      <td>27.831812</td>
    </tr>
    <tr>
      <th>26</th>
      <td>104.059228</td>
      <td>30.504364</td>
      <td>104.059088</td>
      <td>30.504385</td>
      <td>13.572521</td>
      <td>16.287025</td>
    </tr>
    <tr>
      <th>27</th>
      <td>104.059088</td>
      <td>30.504385</td>
      <td>104.059058</td>
      <td>30.504385</td>
      <td>2.868188</td>
      <td>3.441826</td>
    </tr>
    <tr>
      <th>28</th>
      <td>104.059058</td>
      <td>30.504385</td>
      <td>104.059038</td>
      <td>30.504385</td>
      <td>1.912123</td>
      <td>2.294548</td>
    </tr>
  </tbody>
</table>
</div>




```python

```

**Comment by kfyidrig** [comment]
![problem](https://user-images.githubusercontent.com/13808186/145829148-28b57df9-fcf5-40eb-a70d-25f6bcfdd8e6.png)
匹配似乎因为参数不巧当结果不太好

**Comment by kfyidrig** [comment]
> 你的r和gps_error设置有问题，需要缩小，单位是你的gps数据的单位，就是经纬度，速度的单位是经纬度每秒，参考[#138 (comment)](https://github.com/cyang-kth/fmm/issues/138#issuecomment-733669669)

你的意思是我的参数都给的太大了对吗（除了k），明天再试试，非常感谢你！！！

**Comment by kfyidrig** [comment]
我经过了几次测试，得到了如下的结果
![always 0](https://user-images.githubusercontent.com/13808186/145940482-7b5b6c7d-0170-4e52-b811-35c825fd5fdf.PNG)
但是速度仍然有问题，某些点速度竟然达到了10的306次方，我应该继续优化参数吗
![config](https://user-images.githubusercontent.com/13808186/145940579-6a68ed8a-eabc-4803-a734-59ec349bc7f1.PNG)
![speed](https://user-images.githubusercontent.com/13808186/145940598-d301feef-e9e9-41ac-a5ee-e8540d241fc3.PNG)
