### ISSUE TITLE
UBODT: the result file is too large and the disk is full

### ISSUE THREAD

**Issue by Fern-Parker** [cyang-kth/fmm#238]
UBODT: the result file is too large and the disk is almost full. I tried 3 times, and got the following: 
Disk size: 20GB, delta: 200, the size of ubodt.txt is up to about 19.8GB
Disk size: 40GB, delta: 5, the size of ubodt.txt is up to about 39GB
Disk size: 80GB, delta: 3, the size of ubodt.txt is up to about 78.9GB

Has anyone ever encountere d this problem？Any help will be greatly appreciated!

**Comment by cyang-kth** [comment]
If you use degrees, reduce delta to by 100000 to change to degree unit.

**Comment by iman4000** [comment]
can you give some explanation for delta parameter and what is this actually?
when we reduce delta, data is bigger. i can not understand why!

**Comment by Fern-Parker** [comment]
您好，您的邮件已收到，我会尽快给您回复
