### ISSUE TITLE
results visualisation

### ISSUE THREAD

**Issue by Sean0719** [cyang-kth/fmm#26]
Hi,

Does there have some codes to visualise the matching results? Just like the figure of input.pnd and output.png? In addition, for my case, when i set the mode to 2, there is no geo information in the mr.txt, could you give me some guidelines? Thank you very much.

Sean

**Comment by cyang-kth** [comment]
There is specific tools designed for visualization of the map matching results. These figures are generated using QGIS, which support a wide range of formats including shapefile, csv. There could be several reasons that no geo information is generated in mr.txt:
1) delta defined in ubodt_gen is too small and gps point are far away from each other
2) Configurations of fmm are not corrected set (too small search radius)
3) the network topology is incomplete, some points cannot be connected 
4) the trajectory itself contains some noise that cannot be handled properly by the program

**Comment by Sean0719** [comment]
Thank you very much.  Could you please tell me the default unit of search  radius (r) (km or m). In addition, every time when i run the fmm_omp fmm_config.xml, i found that the delta ( printed configuration parameter) in the command window is always 5000 even though i change the value in the ubodt_config.xml. So do you know the reason? Thanks for your kind help.

**Comment by cyang-kth** [comment]
The unit of search radius and delta is the same as the unit of the network file. If your network is projected, then the unit will be meter. If it is unprojected, the unit will be degree. 

As for the second problem, it is the default value used in fmm when a routing query is not found in the
ubodt file. That delta value defined ubodt_config.xml is not stored in the ubodt table generated and it cannot be used by the `fmm` program. One potential improvement could be to read this largest value from ubodt.txt as the delta.

**Comment by cyang-kth** [comment]
I have updated the code to correct the printing of delta. When it is unspecified, delta will be read from the ubodt file.

**Comment by Sean0719** [comment]
Okay, thank you very much.
