### ISSUE TITLE
Segmentation fault(Core Dumped)

### ISSUE THREAD

**Issue by Sean0719** [cyang-kth/fmm#27]
Hi Can,

Sorry to disturb you again. I get the edges file via osmnx, but when i change the network type from drive to the drive_service (1787354 edges), this error(segmentation fault) occurred. I am sure that all other parameter are the same.  Could you please give me some suggestion? Thanks in advanced.
############
When run fmm_config.xml
Number of rows read 237211786
    Estimated load factor #elements/#tablebuckets 2.13491
Finish reading UBODT.
    Delta inferred from ubodt as 0.1
Reading meta data of GPS trajectories from: data/trips0306.shp
    Index of ID column: 0
    Total number of trajectories: 33
Finish reading meta data
Write result to file: mr0.1_0.1_0.01.txt
Start to map match trajectories with total number 33
Segmentation fault (core dumped)
###############

Sean

**Comment by cyang-kth** [comment]
Can you send me the network file you used and the trajectory data?

**Comment by Sean0719** [comment]
I send it via email. Thanks.
