### ISSUE TITLE
CMakeLists.txt doesn't exist

### ISSUE THREAD

**Issue by TkMurakami** [cyang-kth/fmm#274]
Trying to follow the installation instructions here: https://github.com/cyang-kth/fmm/tree/master/python

When I run cmake, I get the error: "CMake Error: The source directory '/fmm' does not appear to contain CMakeLists.txt."

I found a similar question on a website(https://github.com/cyang-kth/fmm/issues/38) that has been closed, but I am still unsure how to resolve this issue.

There should be a CMakeLists.txt file in the fmm directory, but I don't understand why this error is occurring. Could you please help me with this?

Thank you.

![スクリーンショット 2024-08-02 20 18 16](https://github.com/user-attachments/assets/d9675e00-7cc8-4823-bb34-ee6491d5186e)

**Comment by cyang-kth** [comment]
If you are running the dockfile, make sure that you run it under the project folder 

- https://github.com/cyang-kth/fmm/tree/master/docker

```bash
# Under the project folder
docker build -f docker/Dockerfile . -t fmm:0.1.0
```

**Comment by TkMurakami** [comment]
I apologize for the delayed response. I was able to run it correctly when I executed it under the project folder. Thank you very much.
