### ISSUE TITLE
UBODT.read_ubodt_csv (Lazy Loading, Chunked Reading) || Python 3.10

### ISSUE THREAD

**Issue by Dh-Kh** [cyang-kth/fmm#275]
I'm encountering memory exhaustion and kernel restarts when attempting to load large UBODT files using UBODT.read_ubodt_csv. Currently, I'm working with an ubodt.txt file containing approximately 2 million rows.

The issue appears to be that the entire UBODT file is loaded into memory at once.This makes it challenging to work with large datasets, especially on systems with limited memory.

**Comment by cyang-kth** [comment]
You may try the stmatch method which does not need to use UBODT but will be slower.
