### ISSUE TITLE
Errors when Rebuild model

### ISSUE THREAD

**Issue by Sean0719** [cyang-kth/fmm#29]
Hi Can,

I download the newversion and when i rebuild the model there is an error appeared. So how can i solve it. Thanks.
###########
app/ubodt_gen.cpp:9:22: fatal error: config.hpp: No such file or directory
 #include "config.hpp"
                      ^
compilation terminated.
make: *** [build_ubodt_gen] Error 1
----- Copy executables to home/bin -----
cp dist/fmm /home/x/bin
cp dist/ubodt_gen /home/x/bin
cp: cannot stat 'dist/ubodt_gen': No such file or directory
make: *** [install] Error 1
################

**Comment by cyang-kth** [comment]
@Sean0719 

Thank you for pointing out this issue. In previous commit I have moved the config.hpp to the src folder, which is not updated in the ubodt apps. I have uploaded the latest code.

**Comment by Sean0719** [comment]
Okay, Thank you very much.

**Comment by Sean0719** [comment]
1 error generated.
make: *** [build_fmm] Error 1
----- Copy executables to home/bin -----
cp dist/fmm /Users/byang/bin
cp: dist/fmm: No such file or directory
make: *** [install] Error 1

**Comment by cyang-kth** [comment]
@Sean0719 
Did you type the make command with `make;make install`?
I have not see this problem. Please check that the executable `fmm` is generated under the folder `dist`.

**Comment by Sean0719** [comment]
Yes, I do this step. Anyway, i will check it. Thanks a lot.
