### ISSUE TITLE
Segmentation fault(Core Dumped)

### ISSUE THREAD

**Issue by Misavan** [cyang-kth/fmm#30]
Hi

When I run fmm it says Segmentation fault(Core Dumped). 

`$ fmm fmm_config.xml
------------ Fast map matching (FMM) ------------
------------     Author: Can Yang    ------------
------------   Version: 2018.03.09   ------------
------------     Applicaton: fmm     ------------
Start reading FMM configuration 
Finish with reading FMM configuration 
Validating configuration for map match application:
    Warning, overwrite existing result file.mr.txt
Validating success.
------------------------------------------
Configuration parameters for map matching application: 
    Network_file:       data/edges_small.shp
    Network id:         id
    Network source:     source
    Network target:     target
    ubodt_file:         ubodt.txt
    multiplier:         100
    nhash:              23100
    delta:              undefined, to be inferred from ubodt file
    ubodt format(1 binary, 0 csv): 0
    gps_file:           data/trips_small.shp
    gps_id:             id
    k:                  10
    radius:             4
    gps_error:          50
    penalty_factor:     0
    result_file:        mr.txt
    Output fields:      
        ogeom
        opath
        pgeom
        offset
        error
        spdist
        cpath
        tpath
        mgeom
------------------------------------------
Read network shp file from data/edges_small.shp
Id column id
	Number of edges in file: 52
	SHP ID idx: 0
	SHP source idx: 1
	SHP target idx: 2
	Geometry type is Line String
	SRID is 4326
Read network finish.
	The maximum node ID is 686801
	Total number of edges read 52
Start to construct boost rtree
Finish construct boost rtree
Reading UBODT file (CSV format) from: ubodt.txt
    Header line skipped.
    Number of rows read 310
    Estimated load factor #elements/#tablebuckets 0.0134199
Finish reading UBODT.
    Delta inferred from ubodt as 0.00980391
Reading meta data of GPS trajectories from: data/trips_small.shp
    Index of ID column: 0
    Total number of trajectories: 81
Finish reading meta data
Write result to file: mr.txt
Start to map match trajectories with total number 81
Progress 0 / 81
Segmentation fault (core dumped)
`
Ubodt worked fine

`$ ubodt_gen ubodt_config.xml
------------ Fast map matching (FMM) ------------
------------     Author: Can Yang    ------------
------------   Version: 2018.03.09   ------------
------------Application: ubodt_gen_opt------------
Read configuration from xml file: ubodt_config.xml
Validating configuration for UBODT construction:
    Warning, overwrite existing result file.ubodt.txt
Validating success.
------------------------------------------
Configuration parameters for UBODT construction: 
    Network_file:       data/edges_small.shp
    Network id:         id
    Network source:     source
    Network target:     target
    delta:              0.01
    Output file:        ubodt.txt
    Output format(1 binary, 0 csv): 0
------------------------------------------
Write UBODT to file ubodt.txt
Read network shp file from data/edges_small.shp
Id column id
	Number of edges in file: 52
	SHP ID idx: 0
	SHP source idx: 1
	SHP target idx: 2
	Geometry type is Line String
	SRID is 4326
Read network finish.
	The maximum node ID is 686801
	Total number of edges read 52
Construct graph from network edges start
Network edges :52 
Graph nodes 53
Construct graph from network edges end
Upperbound config (delta): 0.01
Start to generate UBODT with delta 0.01
Output format csv
Progress 0 / 53
Progress 10 / 53
Progress 20 / 53
Progress 30 / 53
Progress 40 / 53
Progress 50 / 53
Time takes 0.007
Cleaning network
Cleaning network finished
------------    Program finished     ------------
`

Can you please tell me where is my issue. In attached is my data

Best regards,
Michael
[example_small.zip](https://github.com/cyang-kth/fmm/files/3106426/example_small.zip)

**Comment by cyang-kth** [comment]
Hi, @Misavan 

There are two problems:

- The trajectory as input should have geometry type of polyline instead of point. It causes segment fault error.
- The topology of your network seems to be incomplete (orange line) . After I convert the points to a line (blue line), they still cannot be matched as some part of the network should be bi-directional. 

![Screenshot from 2019-04-23 10-50-38](https://user-images.githubusercontent.com/6810084/56567673-b7e16a00-65b5-11e9-873d-54d9b5ee8160.png)

**Comment by Misavan** [comment]
Now I understand. Thank you very much for help
