### ISSUE TITLE
Matched percentage: 0

### ISSUE THREAD

**Issue by Misavan** [cyang-kth/fmm#32]
Hi
When I run fmm it doesn't find any matches, the result <cpath/> is empty
[fmm.zip](https://github.com/cyang-kth/fmm/files/3232802/fmm.zip)

**Comment by cyang-kth** [comment]
There are several problems here. 

In the configuration file, the delta, search radius and gps error you defined is in degree, given your original data in lat,long. You should reduce these values. The delta = 3 equals to 300 km distance. That is why the ubodt file generated is also quite big. You can reduce the value to 3km, 0.03.
