### ISSUE TITLE
How to deal with road priority?

### ISSUE THREAD

**Issue by applefl** [cyang-kth/fmm#35]
Roads in the real world have different levels, such as highways, trunk, motorway, and residential roads. Can this algorithm handle different road priorities?

**Comment by cyang-kth** [comment]
For this approach, it would be very hard to integrate those information into the model. The approach directly retrieves the shortest path distance from a precomputed table. To consider road network, the roads with a higher level could have their length decayed. But I am not quite sure if it is the best way to solve this problem. Maybe you should also refer to some articles for addressing this issue.
