### ISSUE TITLE
Can you provide a python package for ubodt_gen?

### ISSUE THREAD

**Issue by liuyukid** [cyang-kth/fmm#37]
Although I can use the fmm package (python), fmm needs to use the ubodt_gen(c++) to generate ubodt.txt. I think this is very troublesome，could you provide a python package for ubodt_gen? Or can you integrate ubot_gen into fmm(python)? Thank you!

**Comment by cyang-kth** [comment]
Thank you for this suggestion. Since the `ubodt_gen` is only called once in the map matching as a preprocess step, I cannot see a reason that you need to call the program directly in Python.
