### ISSUE TITLE
CMakeLists.txt doesn't exist

### ISSUE THREAD

**Issue by edibusl** [cyang-kth/fmm#38]
Trying to follow the installation instructions here: https://github.com/cyang-kth/fmm/tree/master/python

When running `cmake ..` an error is shown:
```CMake Error: The source directory "/home/edi/code/fmm/python" does not appear to contain CMakeLists.txt.```

It looks like this file is in `.gitignore`

**Comment by cyang-kth** [comment]
@edibusl 
It is quite strange. I clone the project to another folder on my machine. It can find the file correctly. Did you check the file in the python folder? There should be a file called `CMakeLists.txt`.

**Comment by cyang-kth** [comment]
The file is not included in the gitignore. 

```
# Cmake

build/
cmake-build-debug/
CMakeLists.txt.user
CMakeCache.txt
CMakeFiles
CMakeScripts
Testing
cmake_install.cmake
install_manifest.txt
compile_commands.json
CTestTestfile.cmake
_deps
```

**Comment by edibusl** [comment]
I used an outdated version, sorry.
Thanks for help!
