### ISSUE TITLE
how to run fmm in bat file

### ISSUE THREAD

**Issue by earthja123** [cyang-kth/fmm#40]
Since i have many cases to run map matching model (C++), bat file would be my basic needs. I have little knowledge on programming. As far as i search the bat script to run cygwin might look like the follows:
"C:\cygwin64\bin\mintty /bin/bash -l c:\path\to\your\script"

However after i run, program just stop and show only the header:

------------ Fast map matching (FMM) ------------
------------     Author: Can Yang    ------------
------------   Version: 2018.03.09   ------------
------------  Application: ubodt_gen ------------
Read configuration from xml file: ubodt_config.xml

could you please help on this issue.

**Comment by cyang-kth** [comment]
@earthja123 
Since you are using cygwin, you should be able to run bash file from the terminal of cygwin.

You can create a file called `run.sh` with the following content

```
fmm fmm_config1.xml > fmm_config1.log
fmm fmm_config2.xml > fmm_config2.log
fmm fmm_config3.xml > fmm_config3.log
fmm fmm_config4.xml > fmm_config4.log
```

Then you can type the terminal with
```
chmod +x run.sh
./run.sh
```

You can see the log information in `fmm_configX.log`.

**Comment by earthja123** [comment]
@cyang-kth 

thank you very much.

you save my life.
