### ISSUE TITLE
error in my output

### ISSUE THREAD

**Issue by miaomiaomao** [cyang-kth/fmm#43]
Sorry to disturb you again.
There's some error in my output. When I checked 'pgeom', I found that some gps point were matched with '0 0'.
Here is the input:
LINESTRING (-8.618643 41.141412,-8.618499 41.141376,-8.620326 41.14251,-8.622153 41.143815,-8.623953 41.144373,-8.62668 41.144778,-8.627373 41.144697,-8.630226 41.14521,-8.632746 41.14692,-8.631738 41.148225,-8.629938 41.150385,-8.62911 41.151213,-8.629128 41.15124,-8.628786 41.152203,-8.628687 41.152374,-8.628759 41.152518,-8.630838 41.15268,-8.632323 41.153022,-8.631144 41.154489,-8.630829 41.154507,-8.630829 41.154516,-8.630829 41.154498,-8.630838 41.154489)
Here is the output:
LINESTRING (-8.61862328389464 41.1414555366075,-8.61849026161021 41.1413952953285,-8.62030524367214 41.1425402664601,-8.622154312869 41.1438113798153,-8.62395062773408 41.144380692548,-8.6266795454238 41.1447604091626,-8.62737261868137 41.1446919580741,-8.63020665338637 41.1452422388008,-8.63283503440671 41.1470000234958,-8.63174708911134 41.1482330307184,-8.62990391694432 41.1503557735519,-8.62913862329367 41.1512383642161,-8.6290736 41.1513117,-8.62881193599271 41.1522096548352,-8.62876464399775 41.1523939459704,-8.62876116165927 41.1524792121554,-8.63084191628064 41.1525937953313,  **0 0**,
-8.6310274 41.1545682,-8.6307169 41.1544924,-8.6307169 41.1544924,-8.63094107531387 41.1546375359879,-8.63095094005297 41.1546296126295)
I generated my dataset by following the step in [https://github.com/cyang-kth/osm_mapmatching](url). 
Then I create input.shp by pyshp.  Here is the code:
```
import shapefile 
import numpy as np
trips=np.load('trips.npy')
w = shapefile.Writer('test')
w.field('id', 'n')
for i in range(len(trips)):
    w.line([trips[i]])
    w.record(i+1)
w.close()
```
I set the config following [https://github.com/cyang-kth/osm_mapmatching/blob/master/ubodt_config.xml](url) and [https://github.com/cyang-kth/fmm/blob/master/example/fmm_config.xml](url). I just changed the **k、r and gps error** in fmm_config.xml.
What do you think is wrong？Thank you very much!

**Comment by cyang-kth** [comment]
@miaomiaomao 

The problem seems to be a bug in the program. Can you share with me the road network data, the trips data and configurations so I can test it on my computer. 

My email is cyang@kth.se.

**Comment by cyang-kth** [comment]
@miaomiaomao 

I have found a bug in the program causing this problem and I have corrected it in the latest commit https://github.com/cyang-kth/fmm/commit/07639bd8e2fdace117be2245296735fa362d31b1.

It only occurs in the `pgeom` so the problem is in the `locate_point_by_offset` function.

The corrected result in QGIS

![Screenshot from 2019-12-10 17-12-05](https://user-images.githubusercontent.com/6810084/70546815-3fdda980-1b70-11ea-8592-48d0b4cac405.png)


I have some other suggestions for you in the email.

**Comment by miaomiaomao** [comment]
I have an additional question. The ogeom、the pgem and the mgeom can matched good in visualization. But when I draw the picture through cpath, it seems that I get the wrong result. I use the id in cpath to get the GPS of the path in 'network_dual.shp'. When I visualize the trip through cpath, I find some roads where cars didn't pass by in cpath. Is thera some thing wrong in my postprocessing?

**Comment by cyang-kth** [comment]
@miaomiaomao 

It seems that there is some error in your implementations of getting the geometry of a complete path or plotting the line. You need to first find the geometry of each edge in Cpath and optionally concatenate those segments into a single line. Then you can visualize it using Python. Make sure that the geometry of those segments are spatial adjacent.

**Comment by miaomiaomao** [comment]
@cyang-kth 
Should I  filter the ID in cpath?

I use the following code to get the list of segmentions:
```
import shapefile
shps=shapefile.Reader('network_dual.shp')
shapes = shps.shapes()
l=[]
for index in range(len(shapes)):
    geometry = shapes[index]
    l.append(geometry.points)

```
Then I use l[id-1] to get the geometry of the segments. Is this correct? And I take the first point in l[id-1] as the starting point, and the last one as the end. 

In my above case, the id 2  [(-8.5872325, 41.145625), (-8.5869838, 41.1453959)] shouldn't occur here. And many segments I got can't be spatial adjacent.

**Comment by cyang-kth** [comment]
@miaomiaomao 

The problem is that you are using the index of features in shapefile but the integers in Cpath is the **id attribute** of the features in shapefile. You may need to store the geometries in a dictionary and using the id attribute as the index to fetch the geometry.

**Comment by miaomiaomao** [comment]
Thank you, now I've built my pipline. 
One more question is that I didn't get the whole map in the city I want by following the step 1 in osm_mapmatching tutorial. I didn't use the method which need boundary.geojson. 

`import osmnx as ox
place ="Stockholm, Sweden"
G = ox.graph_from_place(place, network_type='drive',which_result=2)
ox.save_graph_shapefile(G, filename='stockholm')`

After above processing I didn't get a map like you showed in tutorial. It seems that I get a smaller one. In fact, when I search Porto or Stockholm's boundary in openstreetmap. it returns a smaller area than I want. Do you have any suggesstions on getting "boundary.geojson" of a selected city?

**Comment by cyang-kth** [comment]
@miaomiaomao 
You can download the administrative boundaries of a city and its neighboring area from OSM then manually merge the polygons into a large one. You can do it in QGIS.
