### ISSUE TITLE
Features planned

### ISSUE THREAD

**Issue by cyang-kth** [cyang-kth/fmm#52]
Sorted by priority
- [x] Implement another algorithm STMATCH using the current framework 
- [x] Separate HPP into header and source code and define folders of the codes
- [x] Directly use GPS point CSV file as input
- [x] Move OMP to the argument list instead of separate app
- [x] Directly reading network data from OpenStreetMap
- [ ] Add preprocessing trajectory data with line simplification or trajectory smoothing
- [ ] Add one-way attribute for the road network instead of preprocessing

**Comment by dkondor** [comment]
Hi,
I've recently found this repository and found it quite useful.

I might be able to help with directly reading OSM data, as I already have C++ code (based on libosmium) to process and convert OSM to text file or shapefile. I've uploaded it now to github: https://github.com/dkondor/osmconvert

Based on a quick look at network.cpp, I believe creating FMM::NETWORK::Network would be very similar to how I currently create shapefiles, e.g.:
https://github.com/dkondor/osmconvert/blob/master/shp_output.cpp

Let me know if you would be interested in integrating this to fmm.

**Comment by cyang-kth** [comment]
@dkondor 

Thanks for your interest!. It would be of great help if you can join to improve this project.

I actually also start to on it based on the libosmium but have not finished it because I am also busy with other tasks.

You can check the osm branch https://github.com/cyang-kth/fmm/tree/osm It contains
- A very simple method to iterate and read all the ways of an OSM file and insert into the network
- Some changes made to the cmake files (You can ignore this part and use the cmake in the master branch)

https://github.com/cyang-kth/fmm/blob/e2a833c66cf5831aca3709f6ffff256fc9f0cb33/src/network/network.cpp#L36-L48

However I encounter some issues that seems to be quite complicated:
- Adding the libosmium library will introduce some extra dependency like protozero, bz, etc. When I tries to add those libraries into the cmake, I found that several warnings come out because the conda environment is in conflict with the default library on my desktop(Ubuntu 16). 
- During that implementation I also realize that the build of c++ program and the python binding can be placed in the project CMakeLists.txt file then I made some changes to the cmake files as well.  Especially for the cmake files, you can still stick to the two separated cmake files in the master branch and ingore my change in the osm branch. 

Comparing my implementation which is quite simple, I think yours are more functional and robust. I think you can ignore my implementation try to integrate yours, here are some suggestions you may consider useful.
  - Rather than creating a separate class like OSMNetwork, I directly extract two methods `read_ogr_file` and `read_osm_file` and based on the file extension it automatically determines the format to read. So the other parts of the program does not need to be changed
  - I realize that the node ID and edge ID of OSM network seems to be quite big integers. So it is then better to change the two types to be `long long` instead of `int`
https://github.com/cyang-kth/fmm/blob/e2a833c66cf5831aca3709f6ffff256fc9f0cb33/src/network/type.hpp#L22-L23
  - Previously there has been some request for directly reading from OSM file, so I think there is no need to create a shapefile from OSM then import into the program. 
  - According to the one-way attribute of OSM way, an extra edge should be created and reverted and inserted into the road network. That is currently the easiest way to handle it. That part I have not implemented but I think your implementation can support it.
  - Although I think about adding an attribute called one-way for each edge so we can avoid copying the two edges with reverse geometry, it takes some time to redesign some other functions to support this feature (which is also one of the tasks mentioned above). I think it should be pended before the OSM reading is done. 
  - It would be great if your code follows a consistent style (like indentation of 2) and contains necessary documentation https://google.github.io/styleguide/cppguide.html

**Comment by dkondor** [comment]
Sounds good, I did not notice the osm branch :)

I think I can easily extend the Network::read_osm_file() function based on the code I had. I'll work on this in the osm branch in my fork and let you know how it goes.

Based on my experience of working with OSM data files, I think there are two main issues:

1. OSM ways do not generally map well to graph edges. A way can include many segments spanning multiple intersections (e.g. https://www.openstreetmap.org/way/194772582 ) or a road segment between two intersection can be made up of multiple ways (e.g. https://www.openstreetmap.org/way/635391879 and https://www.openstreetmap.org/way/635392774 ). This makes it necessary to detect edges bsaed on the connectivity of OSM nodes (the logic I wrote in OSMMap::generate_simplified_graph()). So far, I've found this only possible to do if I first read into memory all nodes and ways. This also means that OSM way IDs are not necessray unique, so some relabeling might be needed.

2. Ways in OSM can denote anything (they are more like the equivalent of generic linestrings), even the boundaries of buildings, e.g. this is technically a way as well: https://www.openstreetmap.org/way/158234017 -- thus it is necessary to do some filtering to identify road types.


Regarding cmake, I have very little experience. I was able to build it without errors in the osm branch as well (I'm on Ubuntu 18.04, and using the system libraries for osmium and gdal).

**Comment by cyang-kth** [comment]
I never notice this geometry issue of OSM data. I expect it to be a quite complex task to extract a routable and correctly connected network from OSM. The current way I handle it is to use [osmnx](https://github.com/gboeing/osmnx) to download a routable road network for a small area or using [osm2pgrouting](https://github.com/pgRouting/osm2pgrouting) to extract a large network. Perhaps it could be useful to refer to those repositories about how to handle the split-merge of road edges and relabeling id of edges. 

- OSMX also provides some options to filer based on network type https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.downloader.get_osm_filter
- Simplify a network https://osmnx.readthedocs.io/en/stable/osmnx.html#module-osmnx.simplify

**Comment by dkondor** [comment]
Hi,
I've just created a PR with a basic implementation; it was actually simpler than I expected.

So far it works well in a simple testcase (see https://github.com/dkondor/fmm/blob/osm/example/command_line_example/osm_test.md ), but there are some issues:

 - Mainly, edge IDs are just arbitrary numbers, since I did not want to use OSM way IDs (an edge can correspond to multiple ways or a way can correspond to multiple edges), so this way, the cpath field in the output is not useful. Maybe there could be a switch to output the node IDs in the cpath instead which should be unique. Or a user could be required to do a preprocessing first to assign unique edge IDs? It depends whether you want to make it possible to use fmm with data downloaded from OSM directly without preprocessing.
 - Which ways are included in the network is not entirely consistent with osmnx's filter (see https://github.com/gboeing/osmnx/blob/46ed807f870e3bede78f7e494e98490df470bd42/osmnx/downloader.py#L19 ); but it would be very simple to modify the way_filter class to use exactly the same criteria. Again, this filtering is needed if the users are not expected to run preprocessing. This is something I can easily add, or even haven option corresponding to the 'network_type' parameter in osmnx.
 - The network might not be connected and might contain "sources" or "sinks" (nodes with only incoming / outgoing edges -- this is either an error on OSM, or more likely the result of cutting a road network to some bounding box). This can result in some O/D pairs not being routable. My code included a part for identifying connected components, but I did not add it here, since this might be handled better in the Network class, if at all.

Let me know what you think or if you see any issues.

**Comment by dkondor** [comment]
>     * OSMX also provides some options to filer based on network type https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.downloader.get_osm_filter
Yes, this is used by default in all the methods that download data, e.g. graph_from_place

> 
>     * Simplify a network https://osmnx.readthedocs.io/en/stable/osmnx.html#module-osmnx.simplify
My understanding is that this is done automatically by graph_from_place() and similar functions (the 'simplify' parameter corresponds to whether it should be done and it is True by default)

**Comment by cyang-kth** [comment]
The OSM data support has been added till this commit 6fc7f240567241af52792e0138b26e3eea2121d0. 
The last two tasks are created as two separate feature request #84 and #85 and this issue is closed.
