### ISSUE TITLE
Some problems running with the example

### ISSUE THREAD

**Issue by wangyong01** [cyang-kth/fmm#53]
**Describe the bug**
I tried to run the example with default and the osm version configurations of ubodt and fmm, but both got 0% matched percentage on the example. Besides, there is a warning with Boost. I am using MAC with Boost 1.69.0.

**Expected behavior**
Here is the configuration on the example.
```
// ubodt_config.xml
<?xml version="1.0" encoding="utf-8"?>
<ubodt_config>
    <input>
        <network>
            <file>../example/data/edges.shp</file>
            <id>id</id>
            <source>source</source>
            <target>target</target>
        </network>
    </input>
    <parameters>
        <delta>0.5</delta>
    </parameters>
    <output>
        <file>ubodt.txt</file>        
    </output>
</ubodt_config>
//fmm_config.xml
<?xml version="1.0" encoding="utf-8"?>
<fmm_config>
  <input>
    <ubodt>
      <file>ubodt.txt</file>
    </ubodt>
    <network>
      <file>../example/data/edges.shp</file>
      <id>id</id>
    </network>
    <gps>
      <file>../example/data/trips.shp</file>
      <id>id</id>
    </gps>
  </input>
  <parameters>
    <k>40</k>
    <r>0.01</r>
    <pf>0</pf>
    <gps_error>0.005</gps_error>
  </parameters>
  <output>
    <fields>
      <all/>
      <!-- <ogeom/> <error/> <opath/> <cpath/> -->
    </fields>
    <file>mr.txt</file>
  </output>
  <other>
    <log_level>2</log_level>
  </other>
</fmm_config>
```

Here is the matching result.
------------ Fast map matching (FMM) ------------
------------     Author: Can Yang    ------------
------------   Version: 2020.01.31   ------------
------------     Applicaton: fmm     ------------
Start with reading FMM configuration ../example/fmm_config.xml
Finish with reading FMM configuration.
Set log level as 2-info
[info][config.hpp:386] Validating configuration
[warning][config.hpp:417] Overwrite existing result file mr.txt
[info][config.hpp:436] Validating done
------------------------------------------------
FMM Configurations
  Network_file: ../example/data/edges.shp
  Network id: id
  Network source: source
  Network target: target
  ubodt_file: ubodt.txt
  delta: undefined, to be inferred from ubodt file
  ubodt format(1 binary, 0 csv): 0
  gps_file: ../example/data/trips.shp
  gps_id: id
  k: 40
  radius: 0.01
  gps_error: 0.005
  penalty_factor: 0
  log_level:2-info
  result_file:mr.txt
  Output fields:
    ogeom  opath  pgeom  offset  error  spdist  cpath  tpath  mgeom  ep  tp  length 
------------------------------------------
[info][network.hpp:74 ] Read network from file ../example/data/edges.shp
[info][network.hpp:172] Read network done edges 17 nodes 30 srid 4326
[info][ubodt.hpp:280] Reading UBODT file (CSV format) from ubodt.txt
[info][ubodt.hpp:316] Finish reading UBODT with rows 0
[info][fmm.cpp:67 ] Delta inferred from ubodt as 0
[info][reader.hpp:81 ] Reading GPS trajectories GDAL format from ../example/data/trips.shp
[info][reader.hpp:109] Geometry type is Line String
[info][reader.hpp:111] Index of id column 0
[info][reader.hpp:112] Total number of trajectories 3
[info][reader.hpp:113] Finish reading meta data
[info][writer.hpp:46 ] Write result to file mr.txt
[info][fmm.cpp:83 ] Total trajectory number 3
[info][fmm.cpp:84 ] Progress report step 10
[info][fmm.cpp:112] Progress 3
[info][fmm.cpp:122] Time takes 0.06, excluding input takes
[info][fmm.cpp:123] Total points 17 matched 0
[info][fmm.cpp:124] Matched percentage: 0
[info][fmm.cpp:127] Point match speed: 0 pt/s (excluding input -nan pt/s)
------------    Program finished     ------------

Process finished with exit code 0

Here is the boost warning.

Scanning dependencies of target fmm
[ 50%] Building CXX object CMakeFiles/fmm.dir/app/fmm.cpp.o
In file included from /Users/yong/Code/fmm/app/fmm.cpp:17:
In file included from /Users/yong/Code/fmm/app/../src/network.hpp:24:
In file included from /Users/yong/Code/fmm/app/../src/types.hpp:14:
In file included from /Users/yong/Code/fmm/app/../src/geometry_type.hpp:10:
In file included from /Users/yong/Code/fmm/include/boost/geometry/extensions/gis/io/wkb/read_wkb.hpp:18:
In file included from /Users/yong/Code/fmm/include/boost/geometry/extensions/gis/io/wkb/detail/parser.hpp:32:
In file included from /Users/yong/Code/fmm/include/boost/geometry/extensions/gis/io/wkb/detail/endian.hpp:29:
In file included from /usr/local/include/boost/detail/endian.hpp:9:
/usr/local/include/boost/predef/detail/endian_compat.h:11:9: warning: The use of BOOST_*_ENDIAN and BOOST_BYTE_ORDER is deprecated. Please include <boost/predef/other/endian.h> and use BOOST_ENDIAN_*_BYTE instead [-W#pragma-messages]
#pragma message("The use of BOOST_*_ENDIAN and BOOST_BYTE_ORDER is deprecated. Please include <boost/predef/other/endian.h> and use BOOST_ENDIAN_*_BYTE instead")
        ^
1 warning generated.
[100%] Linking CXX executable fmm
[100%] Built target fmm

Build finished

**Comment by cyang-kth** [comment]
@wangyong01 

The ubodt.xml file you provided use a upper bound of 0.5, which is too small compared with the one given in the example

https://github.com/cyang-kth/fmm/blob/4e6bba2fa8707cf6967decf5e2a12467e6984ec1/example/ubodt_config.xml#L12
