### ISSUE TITLE
Cannot run ubodt_gen -- help_specified uninitialized

### ISSUE THREAD

**Issue by dkondor** [cyang-kth/fmm#61]
**Describe the bug**
Cannot run ubodt_gen; it just prints out the help message and exits, regardless of options. This happens with both command line options and xml config file.

I suspect that the variable help_specified is uninitialized in the class UBODTGenAppConfig

**Expected behavior**
ubodt_gen processes the network.

**Screenshots**
../../build/ubodt_gen ubodt_config.xml
[info][ubodt_gen_app_config.cpp:28 ] Read configuration from xml file: ubodt_config.xml
[info][ubodt_gen_app_config.cpp:38 ] Read configuration from xml file done
ubodt_gen argument lists:
--network (required) <string>: Network file name
--output (required) <string>: Output file name
--id (optional) <string>: Network id name (id)
--source (optional) <string>: Network source name (source)
--target (optional) <string>: Network target name (target)
--delta (optional) <double>: upperbound (3000.0)
--log_level (optional) <int>: log level (2)
--use_omp: use OpenMP or not
-h/--help: help information
For xml configuration, check example folder

**Comment by dkondor** [comment]
The following change fixes the issue for me (i.e. adding initialization to the constructor in line 10 of src/mm/fmm/ubodt_gen_app_config.cpp):

diff --git a/src/mm/fmm/ubodt_gen_app_config.cpp b/src/mm/fmm/ubodt_gen_app_config.cpp
index e0eece6..bd9af4e 100644
--- a/src/mm/fmm/ubodt_gen_app_config.cpp
+++ b/src/mm/fmm/ubodt_gen_app_config.cpp
@@ -7,7 +7,7 @@ using namespace FMM::CORE;
 using namespace FMM::NETWORK;
 using namespace FMM::MM;
 using namespace FMM::CONFIG;
-UBODTGenAppConfig::UBODTGenAppConfig(int argc, char **argv) {
+UBODTGenAppConfig::UBODTGenAppConfig(int argc, char **argv):help_specified(false) {
   spdlog::set_pattern("[%^%l%$][%s:%-3#] %v");
   if (argc==2) {
     std::string configfile(argv[1]);



Let me know if I should create a pull request.
Thank you!

**Comment by cyang-kth** [comment]
@dkondor 

Thank you for this information. I actually do not encounter this problem but it is definitely a potential bug there. 

To keep it consistent with the other config class, it may be better to change it here in the header class. 

https://github.com/cyang-kth/fmm/blob/d0ad943aeb5613703a2243fdc5fbccfc4f34d1b8/src/mm/fmm/ubodt_gen_app_config.hpp#L65

https://github.com/cyang-kth/fmm/blob/d0ad943aeb5613703a2243fdc5fbccfc4f34d1b8/src/mm/fmm/fmm_app_config.hpp#L66

https://github.com/cyang-kth/fmm/blob/d0ad943aeb5613703a2243fdc5fbccfc4f34d1b8/src/mm/stmatch/stmatch_app_config.hpp#L65

You can check if that works and create a pull request.
Thanks a lot for your help.

**Comment by dkondor** [comment]
OK, great, I'll do. Thank you for the quick reply.
