### ISSUE TITLE
About trips.csv

### ISSUE THREAD

**Issue by michealowen** [cyang-kth/fmm#64]
I have problems in generating the trips.csv. It was written like this in the tutorial, "a CSV file with a header row and columns separated by ;. Each row stores a trajectory with geometry in WKT linestring format. ". And I tried to generate the trips.csv based on my own data using the PostGis function st_asewkt(). The content of my trips.csv is as follows.
id;geom
1;LINESTRING(113.614631	34.736674,113.605426 34.734395,113.614563 34.73697,113.614807 34.736701,113.614854 34.737817,113.606819	34.733816,113.614959 34.73763,113.614956 34.740037,113.61473 34.73919,113.614869 34.740257,113.614775 34.740217)

When i use the command below

1.fmm fmm_config_csv_trajectory.xml
2.fmm --ubodt ubodt.txt --network ../data/edges.shp --gps ../data/trips.csv -k 4 -r 0.4 -e 0.5 --output mr.txt
I failed to match the trajectory.

**Comment by cyang-kth** [comment]
@michealowen 
I think your trajectory is too complicated to be matched as when I visualize it

![image](https://user-images.githubusercontent.com/6810084/80822514-2a2e5680-8bdb-11ea-907c-07e59670f5e5.png)

I think perhaps you need to preprocess it or smooth it.

**Comment by michealowen** [comment]
Oh, I see.Thank u for pointing out the problem.
