### ISSUE TITLE
empty results

### ISSUE THREAD

**Issue by aminissn** [cyang-kth/fmm#66]
I have followed the instruction to do a map matching on OSM network. Ther are 2 issues which I like to ask:
1) I think ubodt_gen has a bug in '--id' flag. currently, despite the help, it works ith --network_id (as it is in fmm). However, in xml config file id is just fine.
2) I get empty results from fmm map matching. Here again when I use the command line it says 
[critical][gps_reader.cpp:128] Id assetid or Geometry column geom not found
but when I use the fmm config file I just get empty results. Both my shapefile and trajectories are in EPSG:4326. Could you perhaps give me some hints about what could be wrong with my approach? 
I have a feeling that the program doesn't see the geometries at all

**Comment by aminissn** [comment]
Just to add one more thing: when I test with another CSV file 2 of the 100 points are matched. Again when I use the command line instead of xml config file I always get an error saying:
 [critical][gps_reader.cpp:128] Id itrack_id or Geometry column geom not found even though I specify the column names correctly. Using config file is just fine.

**Comment by cyang-kth** [comment]
@aminissn 

Thank you for mentioning this problem. 
The first issue you mentioned with `ubodt_gen` is a bug in the program where the help information is not consistent with the one used in the input. 

https://github.com/cyang-kth/fmm/blob/dafe91305781cbc4b12432b795a2428866076141/src/mm/fmm/ubodt_gen_app_config.cpp#L49

https://github.com/cyang-kth/fmm/blob/dafe91305781cbc4b12432b795a2428866076141/src/mm/fmm/ubodt_gen_app_config.cpp#L93

https://github.com/cyang-kth/fmm/blob/dafe91305781cbc4b12432b795a2428866076141/src/config/network_config.cpp#L25

For the problem with GPS data, I think the CSV file should be 
- column separated by `;`
- if you are using point CSV as input (each line is a point), then the gps_x and gps_y should be specified to define the geometry. If you are using trajectory CSV as input (each line is a trajectory), then you need to use gps_geom to define the geometry. 

I think you need to provide more details like the command you executed and perhaps a sample of the GPS data or a small network. Then I can check what is the problem there.

**Comment by aminissn** [comment]
Thanks for the quick reply. I will gladly share my experience.The csv file format should be correct, as I get two points matched. Interestingly, these are single points, no other point with the vehicle id! I copied all the files on Google Drive: https://drive.google.com/drive/folders/1Z8Z3n4c07Kwi3FoM3O8zS3hYkPiEvCUN?usp=sharing

**Comment by aminissn** [comment]
another update: I think the main problem with the first query was the map. I am interested in freeway gps only on a large scale and to reduce the size of the map I used filters. When I use another map it works! I used convertor suggested @dkondor since osmnx in Python couldn't handle the large map. NOw I get all 114 points matched. However, the command line is still not working!

**Comment by cyang-kth** [comment]
@aminissn 

Your network is not connected with this part missing. 

![a](https://user-images.githubusercontent.com/6810084/81743883-ae69bf00-94a2-11ea-9490-c4e404d6e270.png)


Another problem I found with the test1.csv is that the ID is not an integer, which could cause problems in parsing the data. 

But your error showing that 
```
[critical][gps_reader.cpp:128] Id assetid or Geometry column geom not found
```
which is inside the trajectory CSV reader function, I think that is also a problem.  

https://github.com/cyang-kth/fmm/blob/dafe91305781cbc4b12432b795a2428866076141/src/io/gps_reader.cpp#L128

**Comment by cyang-kth** [comment]
@aminissn 

Sorry for this problem. I found that it is missing an argument of 
```
--gps_point
```

If you compare the command line argument here

https://github.com/cyang-kth/fmm/tree/master/example/command_line_example
```
# XML configuration
fmm fmm_config_csv_point.xml
# Command line arguments
fmm --ubodt ubodt.txt --network ../data/edges.shp --gps ../data/gps.csv --gps_point -k 4 -r 0.4 -e 0.5 --output mr.txt
```

The current print help, especially for the argument parsing, needs to be updated. Currently each program defines its own help and argument parser. I think it needs to be redesigned to avoid those mistakes.

**Comment by aminissn** [comment]
thanks! it actually works even with non-integer IDs, it just ignores everything before the first non-zero digit.

**Comment by cyang-kth** [comment]
@aminissn 

I have just pushed a commit afb3d926ab171fe83bfc7e88441d6bb1c0c01853 to fix these inconsistencies in help information. You can pull the latest version from the master branch and rebuild it. 

It would be better to use integer rather than a string to make sure that it is distinct if some part is dropped.

**Comment by cyang-kth** [comment]
This issue is fixed at https://github.com/cyang-kth/fmm/commit/afb3d926ab171fe83bfc7e88441d6bb1c0c01853 and closed.
