### ISSUE TITLE
Partly match a trajectory

### ISSUE THREAD

**Issue by cyang-kth** [cyang-kth/fmm#69]
If some parts of a trajectory cannot be matched, export a partly match result, which is a MultiLineString.

**Comment by cyang-kth** [comment]
In progress with Implementing in this branch 
https://github.com/cyang-kth/fmm/tree/feature-partial-match

**Comment by ziXet** [comment]
This is an interesting feature. Would you please provide a progress update? I might be able to contribute...

**Comment by cyang-kth** [comment]
Feature already implemented. It will be pushed after our next paper is published.
