### ISSUE TITLE
Minor issue: wrong srid output print from ubodt_gen_omp?

### ISSUE THREAD

**Issue by davmol** [cyang-kth/fmm#72]
The srid output of the network read is always 4326 though the shapefiles srid is 32632. The Afterwards the graph is also working as intended with 32632 coordinates and its unit in meters.

```
$ ubodt_gen_omp ubodt_config.xml
------------ Fast map matching (FMM) ------------
------------     Author: Can Yang    ------------
------------   Version: 2020.01.31   ------------
------------Application: ubodt_gen_omp------------
Read configuration from xml file: ubodt_config.xml
Set log level as 2-info
[info][config.hpp:607] Validating configuration for UBODT construction
[info][config.hpp:636] Validating done.
------------------------------------------
UBODT Configuration:
  Network_file: data/network_deu_32632_6.shp
  Network id: id
  Network source: source
  Network target: target
  delta: 100
  Output file:data/ubodt_deu_100_32632_6.bin
  Output format(1 binary, 0 csv): 1
  log_level:2-info
------------------------------------------
[info][ubodt_gen_omp.cpp:39 ] Write UBODT to file data/ubodt_deu_100_32632_6.bin
[info][network.hpp:74 ] Read network from file data/network_deu_32632_6.shp
[info][network.hpp:171] Read network done edges 7119308 nodes 15997094 srid 4326
...
```

**Comment by cyang-kth** [comment]
Currently the srid is not used in the process. It is just printed as a log information about the input data. I am not sure if the newest version still has that issue or not.

**Comment by davmol** [comment]
I assumed this. Just thought I wanted to mention since it was a little misleading for me in the beginning and maybe for others too... The output is from the current master version.

**Comment by cyang-kth** [comment]
@davmol 

I agree with that. I think you are still using the older version of the `ubodt_gen_omp`. In the current master version, that app is removed (replaced with `--use_omp` for the `ubodt_gen`). 
 
https://github.com/cyang-kth/fmm/tree/master/example/command_line_example 

The reason is that you still have it is that `ubodt_gen_omp` was copied to bin but it is not deleted.

**Comment by davmol** [comment]
> @davmol
> 
> I agree with that. I think you are still using the older version of the `ubodt_gen_omp`. In the current master version, that app is removed (replaced with `--use_omp` for the `ubodt_gen`).
> 
> https://github.com/cyang-kth/fmm/tree/master/example/command_line_example
> 
> The reason is that you still have it is that `ubodt_gen_omp` was copied to bin but it is not deleted.

That seems absolutely right! Sorry, I haven't noticed the renaming of the program.
