### ISSUE TITLE
reroutes due to gps inaccuracy ST_MATCH vs FMM

### ISSUE THREAD

**Issue by davmol** [cyang-kth/fmm#76]
I'm encountering problems with the routed pathes through my network since the gps points i'm feeding st_match and fmm with are not the most accurate due to inaccuracy from the gps. Here is an st_match example with these input parameters (all via python api): 

k = 8
gps_error = 50
radius = 300
vmax = 80
factor = 1.5

blue large dots: gps point trajectory
black dots: matched points
red line: routed path

![match_7](https://user-images.githubusercontent.com/37088985/82453251-9270a980-9ab0-11ea-9320-8380d71a85a8.PNG)

As shown above there a multiple u-turns because the matched points partly fall on the opposed unidirectional lane. Also there a 2 single punctures in a bidrectional lane that also end up in a u-turn. The GPS points a real world example with a rate of 1point/sec. I'm in before already using the Ramer-Douglas-Peucker algorithm to smooth the trajectory since there a lot of jumpy points when there is no movement of the vehicle (e.g. red traffic light, jams) . This problems shows up mainly in cities where the street network is more complex of course than in rural areas with major roads.

I have the feeling every edge will get routed through with a matched point? Increasing the gps_error doesn't  really help here. Are there any suggestions i could try out to deal with inaccurate gps signal?

However fmm (delta 100 meter) reveales no final routed path but shows mainly the same matched points with the same input parameters as seen in the picture from st_match above.

**Comment by cyang-kth** [comment]
@davmol 

There is no easy way to handle this problem in the map matching. I think it is better to apply filtering or smoothing of the trajectory to create a simple one in the preprocessing stage.

**Comment by davmol** [comment]
I feared this answer. Other mapmatching engines show kind of the same problems with this specific track.
