### ISSUE TITLE
Read shapefile created by OSMNX

### ISSUE THREAD

**Issue by cyang-kth** [cyang-kth/fmm#84]
OSMNX is intensively used for creating a routable OSM network in shapefile. A mode parameter can be supplied to the network reader to read this special type of network.

**Comment by NPUStephenHao3023** [comment]
when i use osmnx to save chengdu road network data in shapefile , it failed. I think map data is crucially important for beginners

**Comment by cyang-kth** [comment]
@NPUStephenHao3023  I think it is an issue with the osmnx. Otherwise you can also use osm official website to download the data.

**Comment by cyang-kth** [comment]
This issue is closed as the tutorial https://github.com/cyang-kth/osm_mapmatching#1-download-routable-network-from-osm gives an illustration for using OSMNX network as input.

**Comment by NPUStephenHao3023** [comment]
@cyang-kth Thank you so much for give the script to convert osm map data.☺
