### ISSUE TITLE
Map Matching with a generic ShapeFile

### ISSUE THREAD

**Issue by williamgrimes** [cyang-kth/fmm#92]
This seems like a very nice project, and I'm very keen to try matching GPS traces to a map!

I've been experimenting using this solution with a shapefile and GPS traces I have, but could use some guidance to achieve results

The shapefile I have looks something like this:

```
ID        geometry
47194001  LINESTRING (23994.000 397505.000, 23958.000 39...
46184029  LINESTRING (23213.000 392258.000, 23199.000 39...
46184031  LINESTRING (23240.000 392234.000, 23213.000 39...
96204004  LINESTRING (48377.000 402112.000, 48291.000 40...
96204013  LINESTRING (48432.000 401949.000, 48395.000 40... 
```

Where the geometry describes an edge and each edge has an associated ID, these are roads in a network so can be considered a directed graph. In your documentation I can see that the input file should have a `source` and `target` field, so I created two string fields using the first and last point of the LINESTRING, i.e.

```
ID        geometry                                            source              target
47194001  LINESTRING (23958.000 397503.000, 23994.000 39...   (23958.0, 397503.0) (23994.0, 397505.0)
46184029  LINESTRING (23199.000 392248.000, 23213.000 39...   (23199.0, 392248.0) (23213.0, 392258.0)
46184031  LINESTRING (23213.000 392258.000, 23240.000 39...   (23213.0, 392258.0) (23240.0, 392234.0)
96204004  LINESTRING (48255.000 402163.000, 48263.000 40...   (48255.0, 402163.0) (48377.0, 402112.0)
96204013  LINESTRING (48385.000 402035.000, 48391.000 40...   (48385.0, 402035.0) (48432.0, 401949.0)
```

The source and target fields are strings, and should in effect be the nodes in this graph. This seems okay, but when I experiment with loading this network using the `stmatch_example.ipynb` as a template

```
print "Nodes {} edges {}".format(network.get_node_count(),network.get_edge_count())
graph = NetworkGraph(network)
model = STMATCH(network,graph)
```
I get the following output: `Nodes 1 edges 2118726`

This is the correct number of edges but I should have more nodes?

How can I work with the above kind of generic shapefile describing, with an `id` and `geometry` field?

**Comment by cyang-kth** [comment]
@williamgrimes 
Generally, the source and target geometry of a network should be integers. The fields you created as string may not be parsed correctly so it detects as a single node. 

One way to generate topology (source and target fields) of a generic network is to use https://docs.pgrouting.org/2.2/en/src/topology/doc/pgr_createTopology.html offered by pgRouting. 

The function may be integrated into the project as 
- A command tool for creating/export topology from a shapefile may be added as a new feature.  
- Another mode for directly reading point to create topology, which may be hard to verify the result especially nodes of the graph.

**Comment by williamgrimes** [comment]
@cyang-kth thank you, this worked!

I mapped the `source` and `target` columns to integers as follows:

```
point_map = {k: v for v, k in enumerate((gdf.loc[:, ['source_pt', 'target_pt']].values.flatten()))}
gdf['source'] = gdf['source'].map(point_map)
gdf['target'] = gdf['target'].map(point_map)
```

Now I get a more reasonable network: `Nodes 790568 edges 2118726`

Still I'm not sure if my method of finding the nodes is sufficient, as there maybe floating point errors, and the https://docs.pgrouting.org/2.2/en/src/topology/doc/pgr_createTopology.html you refer to is probably better since it has a `tolerance` parameter. Ideally I would find a solution to this in python, but will investigate further.

One further question looking at your example: https://github.com/cyang-kth/fmm/blob/master/example/notebook/stmatch_example.ipynb

and the Configuration table in the documentation I cannot understand why a maximum vehicle speed `vmax` parameter is necessary and how this would impact my output?

**Comment by cyang-kth** [comment]
@williamgrimes 
The vmax is a maximum speed parameter described in the original paper of stmatch https://dl.acm.org/doi/abs/10.1145/1653771.1653820. It is used to limit the search of routes between consecutive points based on the estimated maximum distance traveled between the two points (f * vmax * time_difference). The unit of vmax is map_unit/second. If your data is projected in unit of meters then vmax of 30 means the maximum speed is 30m/s and 108km/h.

By setting a lower value, you are able to improve the speed but setting a too small value, you may have a wrong matching result.

**Comment by williamgrimes** [comment]
@cyang-kth I've been trying to create a topology with the method you suggested https://docs.pgrouting.org/2.2/en/src/topology/doc/pgr_createTopology.html but am having some issues:

I've loaded my shapefile into a psql table using your helpful guide here:

https://github.com/cyang-kth/osm_mapmatching

Then I create a `source` and `target` column and run the following:

`SELECT pgr_createTopology('network.edges_undirected', 1, 'geom', 'id', 'source', 'target');`

The data is originally is in EPSG:28992 (Netherland's projection) and the above command crucially sets a tolerance of what should be 1 m. According to the `pgr_createTopology` documentation

`tolerance:	float8 Snapping tolerance of disconnected edges. (in projection unit)`

This updates the source and target columns as expected, however when I run the matching (st-match) as in your notebook (https://github.com/cyang-kth/fmm/blob/master/example/notebook/stmatch_example.ipynb).

The topology is not connecting disconnected edges, for example these are lines that should be connected but are not:

```
wkt_geom    ID  
LineString (133544.36799999998765998 446157.12800000002607703, 133552.72000000000116415 446118.25400000001536682, 133574.96700000000419095 446015.36599999997997656)    267292117   
```

```
wkt_geom    ID 
LineString (133574.96700000000419095 446015.36600000195903704, 133616.3809999999939464 445886.26000000099884346, 133637.66000000000349246 445821.24200000101700425, 133655.39199999999254942 445770.40900000202236697, 133659.21599999998579733 445759.97600000305101275, 133672.27624999999534339 445725.43329000298399478)    267292121
```

This means I'm not able to perform the map matching. Do you have any suggestions what I could be doing wrong, here?

**Comment by cyang-kth** [comment]
@williamgrimes 
In your case, it should be a problem with using pgr_createTopology. You need to enlarge the value of tolerance (e.g., 5m or 10m) in order to connect the edges correctly. If some of your edges are bidirectional, you also need to create a reverse edge for them because each edge in the network is considered as single directional. 

https://github.com/cyang-kth/osm_mapmatching#22-complement-bidirectional-edges

**Comment by williamgrimes** [comment]
The tolerance should not be the reason, as you can see between the last point in id `267292117` and the first point in id `267292121` are very close:

```
>>> from shapely.geometry import Point
>>> Point(133574.96700000000419095, 446015.36599999997997656).distance(Point(133574.96700000000419095, 446015.36600000195903704))
```

```
1.979060471057892e-09
```
Thanks for the tip about reversing, I have already done this :-)

**Comment by williamgrimes** [comment]
@cyang-kth update

The implementation problems I outlined in this issue were actually a problem with the geometries of my underlying shapefile having floating point errors, not any issue per se with the FMM library

For me the easiest way to solve was doing some preprocessing to correctly join linestrings in python with geopandas (see):

https://gis.stackexchange.com/a/202903/98837

**Comment by williamgrimes** [comment]
@cyang-kth from your paper https://dl.acm.org/doi/abs/10.1145/1653771.1653820 

```
In this paper, we propose a novel global map-matching algorithm called ST-Matching for low- sampling-rate GPS trajectories. ST-Matching considers (1) the spatial geometric and topological structures of the road network and (2) the temporal/speed constraints of the trajectories. Based on spatio-temporal analysis, a candidate graph is constructed from which the best matching path sequence is identified.```

How come then in your notebook example of ST-Match, you provide a `wkt` but there are no timestamps? Not sure I understand how this temporal aspect can be considered without timestamps?

https://github.com/cyang-kth/fmm/blob/topology/example/notebook/stmatch_example.ipynb

**Comment by cyang-kth** [comment]
@williamgrimes 

Currently the STMATCH algorithm is not exactly the same as the one proposed there as the timestamp information is not fully integrated into the matching as a temporal score and it is just used in limiting the search of shortest paths. When matching the wkt linestring without timestamp, an empty timestamp vector is created to keep the function consistent.

https://github.com/cyang-kth/fmm/blob/f840cbf9f75e3903357c4966bd2cbeaa2b12d902/src/mm/stmatch/stmatch_algorithm.cpp#L85-L87

The search is then bounded to 4 * f * the euclidean distance.  

https://github.com/cyang-kth/fmm/blob/f840cbf9f75e3903357c4966bd2cbeaa2b12d902/src/mm/stmatch/stmatch_algorithm.cpp#L228-L234
